# 05_6 — Consolidação analítica dos dados do SINAN

Este notebook consolida os produtos analíticos produzidos nas diferentes
etapas de análise dos registros de dengue do SINAN.

São integrados produtos provenientes das seguintes dimensões analíticas:

- análises geográficas;
- análises virológicas;
- análises clínicas;
- hospitalização e desfechos;
- autoctonia e fonte provável de infecção;
- análises temporais.

O objetivo desta etapa não é reproduzir as análises realizadas nos
notebooks anteriores, mas organizar seus resultados em uma camada
analítica consolidada, padronizada e rastreável.

Os produtos consolidados serão utilizados posteriormente na geração
de documentos semânticos e na composição do panorama geral dos dados
do SINAN.

A integração considera os diferentes níveis de agregação dos produtos,
evitando a combinação direta de indicadores que possuam granularidades
ou denominadores distintos.

**Resumo** da estrutura proposta do notebook
05_6_consolidacao_analitica_SINAN.ipynb

01. Montagem do Google Drive
02. Imports
03. Configurações e diretórios
04. Definição dos domínios analíticos
05. Localização dos produtos disponíveis
06. Carregamento dos inventários
07. Consolidação dos inventários
08. Validação da estrutura dos produtos
09. Carregamento dos produtos selecionados
10. Consolidação por dimensão analítica
11. Construção de visão consolidada por UF
12. Construção do panorama nacional
13. Metadados e rastreabilidade
14. Produtos finais da consolidação
15. Inventário dos produtos consolidados
16. Salvamento
17. Validação dos arquivos salvos

## 1 - Montagem do drive

In [ ]:
from google.colab import drive
import os

drive.mount("/content/drive")

/content/drive recriado.
Mounted at /content/drive

##2 - Imports

In [ ]:
# ============================================================
# 2 — IMPORTS
# ============================================================

import pandas as pd
import numpy as np
import json

from pathlib import Path

## 3. Configuração

In [ ]:
# ============================================================
# 3 — CONFIGURAÇÕES GERAIS
# ============================================================

ANO = 2026

BASE_DIR = Path(
    "/content/drive/MyDrive/Doutorado/arbovirus_rag"
)

PASTA_ANALYTICS = (
    BASE_DIR
    / "data_analytics"
    / "SINAN"
    / str(ANO)
)

PASTA_SAIDA = (
    PASTA_ANALYTICS
    / "consolidado"
)

PASTA_SAIDA.mkdir(
    parents=True,
    exist_ok=True
)

print(
    f"Ano: {ANO}"
)

print(
    f"Diretório de produtos analíticos:\n"
    f"{PASTA_ANALYTICS}"
)

print(
    f"\nDiretório de saída:\n"
    f"{PASTA_SAIDA}"
)

Ano: 2026
Diretório de produtos analíticos:
/content/drive/MyDrive/Doutorado/arbovirus_rag/data_analytics/SINAN/2026

Diretório de saída:
/content/drive/MyDrive/Doutorado/arbovirus_rag/data_analytics/SINAN/2026/consolidado

## 4 — Definir os domínios analíticos

In [ ]:
# ============================================================
# 4 — DOMÍNIOS ANALÍTICOS
# ============================================================

DOMINIOS_ANALITICOS = {

    "geografico": {
        "nome": "Análises geográficas",
        "pasta": PASTA_ANALYTICS / "geograficos"
    },

    "virologico": {
        "nome": "Análises virológicas",
        "pasta": PASTA_ANALYTICS / "virologicas"
    },

    "clinico": {
        "nome": "Análises clínicas",
        "pasta": PASTA_ANALYTICS / "clinicas"
    },

    "desfechos": {
        "nome": "Hospitalização e desfechos",
        "pasta": PASTA_ANALYTICS / "desfechos"
    },

    "autoctonia": {
        "nome": "Autoctonia e fonte provável de infecção",
        "pasta": (
            PASTA_ANALYTICS
            / "autoctonia"
        )
    },

    "temporal": {
        "nome": "Análises temporais",
        "pasta": PASTA_ANALYTICS / "temporais"
    }
}

In [ ]:
for dominio, configuracao in DOMINIOS_ANALITICOS.items():

    print(
        f"{dominio:<15} "
        f"{configuracao['pasta']}"
    )

geografico      /content/drive/MyDrive/Doutorado/arbovirus_rag/data_analytics/SINAN/2026/geograficos
virologico      /content/drive/MyDrive/Doutorado/arbovirus_rag/data_analytics/SINAN/2026/virologicas
clinico         /content/drive/MyDrive/Doutorado/arbovirus_rag/data_analytics/SINAN/2026/clinicas
desfechos       /content/drive/MyDrive/Doutorado/arbovirus_rag/data_analytics/SINAN/2026/desfechos
autoctonia      /content/drive/MyDrive/Doutorado/arbovirus_rag/data_analytics/SINAN/2026/autoctonia
temporal        /content/drive/MyDrive/Doutorado/arbovirus_rag/data_analytics/SINAN/2026/temporais

## 6 — Validar se as pastas existem

Antes de tentar carregar qualquer arquivo:

In [ ]:
# ============================================================
# VALIDAÇÃO DOS DIRETÓRIOS
# ============================================================

for dominio, configuracao in DOMINIOS_ANALITICOS.items():

    pasta = configuracao[
        "pasta"
    ]

    if pasta.exists():

        print(
            f"OK      {dominio:<15} "
            f"{pasta}"
        )

    else:

        print(
            f"AUSENTE {dominio:<15} "
            f"{pasta}"
        )

OK      geografico      /content/drive/MyDrive/Doutorado/arbovirus_rag/data_analytics/SINAN/2026/geograficos
OK      virologico      /content/drive/MyDrive/Doutorado/arbovirus_rag/data_analytics/SINAN/2026/virologicas
OK      clinico         /content/drive/MyDrive/Doutorado/arbovirus_rag/data_analytics/SINAN/2026/clinicas
OK      desfechos       /content/drive/MyDrive/Doutorado/arbovirus_rag/data_analytics/SINAN/2026/desfechos
OK      autoctonia      /content/drive/MyDrive/Doutorado/arbovirus_rag/data_analytics/SINAN/2026/autoctonia
OK      temporal        /content/drive/MyDrive/Doutorado/arbovirus_rag/data_analytics/SINAN/2026/temporais

## 7 — Listar os arquivos disponíveis por domínio

Antes de carregar qualquer DataFrame, eu faria uma inspeção automática.

In [ ]:
# ============================================================
# ARQUIVOS DISPONÍVEIS POR DOMÍNIO
# ============================================================

for dominio, configuracao in DOMINIOS_ANALITICOS.items():

    pasta = configuracao[
        "pasta"
    ]

    print(
        "\n"
        + "=" * 70
    )

    print(
        configuracao[
            "nome"
        ]
    )

    print(
        "=" * 70
    )

    if not pasta.exists():

        print(
            "Diretório não encontrado."
        )

        continue

    arquivos = sorted(
        pasta.glob("*")
    )

    if len(arquivos) == 0:

        print(
            "Nenhum arquivo encontrado."
        )

    else:

        for arquivo in arquivos:

            print(
                arquivo.name
            )

======================================================================
Análises geográficas
======================================================================
casos_municipio_2026.parquet
casos_uf_notificacao_2026.parquet
casos_uf_residencia_2026.parquet
criticidade_uf_2026.parquet
incidencia_municipio_2026.parquet
inventario_produtos_geograficos_2026.csv

======================================================================
Análises virológicas
======================================================================
completude_sorotipo_uf_2026.parquet
inventario_produtos_virologicos_2026.csv
sorotipos_uf_2026.parquet

======================================================================
Análises clínicas
======================================================================
doencas_preexistentes_brasil_2026.parquet
doencas_preexistentes_uf_2026.parquet
inventario_produtos_clinicos_2026.csv
sintomas_brasil_2026.parquet
sintomas_uf_2026.parquet

======================================================================
Hospitalização e desfechos
======================================================================
doencas_preexistentes_obitos_brasil.parquet
doencas_preexistentes_obitos_uf.parquet
evolucao_brasil.parquet
evolucao_uf.parquet
hospitalizacao_brasil.parquet
hospitalizacao_uf.parquet
inventario_produtos_desfechos.csv
obitos_brasil.parquet
obitos_sorotipo_brasil.parquet
obitos_sorotipo_uf.parquet
obitos_tipo_uf.parquet
obitos_uf.parquet
sintomas_obitos_brasil.parquet
sintomas_obitos_uf.parquet

======================================================================
Autoctonia e fonte provável de infecção
======================================================================
autoctonia_concordancia_municipio.parquet
autoctonia_residencia_brasil.parquet
autoctonia_residencia_uf.parquet
concordancia_municipio_residencia_infeccao.parquet
concordancia_por_uf.parquet
concordancia_uf_residencia_infeccao.parquet
consistencia_autoctonia.parquet
detalhamento_consistencia_autoctonia.parquet
fluxo_municipio_residencia_infeccao.parquet
fluxo_uf_residencia_infeccao.parquet
inventario_produtos_autoctonia_2026.csv
uf_infeccao_autoctonia.parquet
uf_provavel_infeccao.parquet
uf_provavel_infeccao_informada.parquet

======================================================================
Análises temporais
======================================================================
distribuicao_picos_uf.parquet
distribuicao_ultimo_pico_uf.parquet
indicadores_temporais_uf.parquet
inventario_produtos_temporais_2026.csv
pico_comportamento_uf.parquet
resumo_pico_recente.parquet
resumo_temporal_brasil.parquet
resumo_variacao_temporal.parquet
semanas_pico_uf.parquet
serie_temporal_brasil.parquet
serie_temporal_uf.parquet
serie_temporal_uf_normalizada.parquet
variacao_temporal_uf.parquet

## 8 — Criar um primeiro inventário físico dos arquivos

Além dos inventários que cada notebook produziu, podemos criar um inventário baseado no que realmente existe no disco.

In [ ]:
# ============================================================
# INVENTÁRIO FÍSICO DOS ARQUIVOS
# ============================================================

registros_arquivos = []

for dominio, configuracao in DOMINIOS_ANALITICOS.items():

    pasta = configuracao[
        "pasta"
    ]

    if not pasta.exists():
        continue

    for arquivo in pasta.glob("*"):

        registros_arquivos.append({

            "DOMINIO":
                dominio,

            "DOMINIO_DESCRICAO":
                configuracao["nome"],

            "ARQUIVO":
                arquivo.name,

            "EXTENSAO":
                arquivo.suffix.lower(),

            "CAMINHO":
                str(arquivo),

            "TAMANHO_KB":
                round(
                    arquivo.stat().st_size
                    / 1024,
                    2
                )

        })

inventario_fisico = pd.DataFrame(
    registros_arquivos
)

display(
    inventario_fisico
)

,DOMINIO,DOMINIO_DESCRICAO,ARQUIVO,EXTENSAO,CAMINHO,TAMANHO_KB
0,geografico,Análises geográficas,casos_municipio_2026.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,145.23
1,geografico,Análises geográficas,incidencia_municipio_2026.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,175.11
2,geografico,Análises geográficas,criticidade_uf_2026.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,2.77
3,geografico,Análises geográficas,casos_uf_residencia_2026.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,2.59
4,geografico,Análises geográficas,casos_uf_notificacao_2026.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,2.82
5,geografico,Análises geográficas,inventario_produtos_geograficos_2026.csv,.csv,/content/drive/MyDrive/Doutorado/arbovirus_rag...,0.50
6,virologico,Análises virológicas,sorotipos_uf_2026.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,4.24
7,virologico,Análises virológicas,completude_sorotipo_uf_2026.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,6.19
8,virologico,Análises virológicas,inventario_produtos_virologicos_2026.csv,.csv,/content/drive/MyDrive/Doutorado/arbovirus_rag...,0.24
9,clinico,Análises clínicas,sintomas_brasil_2026.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,6.19
10,clinico,Análises clínicas,sintomas_uf_2026.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,14.29
11,clinico,Análises clínicas,doencas_preexistentes_brasil_2026.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,6.03
12,clinico,Análises clínicas,doencas_preexistentes_uf_2026.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,10.91
13,clinico,Análises clínicas,inventario_produtos_clinicos_2026.csv,.csv,/content/drive/MyDrive/Doutorado/arbovirus_rag...,0.59
14,desfechos,Hospitalização e desfechos,hospitalizacao_brasil.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,7.17
15,desfechos,Hospitalização e desfechos,hospitalizacao_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,9.76
16,desfechos,Hospitalização e desfechos,evolucao_brasil.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,3.17
17,desfechos,Hospitalização e desfechos,evolucao_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,8.41
18,desfechos,Hospitalização e desfechos,obitos_brasil.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,2.56
19,desfechos,Hospitalização e desfechos,obitos_tipo_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,3.56
20,desfechos,Hospitalização e desfechos,obitos_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,8.17
21,desfechos,Hospitalização e desfechos,obitos_sorotipo_brasil.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,3.27
22,desfechos,Hospitalização e desfechos,obitos_sorotipo_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,6.66
23,desfechos,Hospitalização e desfechos,doencas_preexistentes_obitos_brasil.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,6.03
24,desfechos,Hospitalização e desfechos,doencas_preexistentes_obitos_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,8.89
25,desfechos,Hospitalização e desfechos,sintomas_obitos_brasil.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,7.28
26,desfechos,Hospitalização e desfechos,sintomas_obitos_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,9.64
27,desfechos,Hospitalização e desfechos,inventario_produtos_desfechos.csv,.csv,/content/drive/MyDrive/Doutorado/arbovirus_rag...,3.13
28,autoctonia,Autoctonia e fonte provável de infecção,autoctonia_residencia_brasil.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,2.55
29,autoctonia,Autoctonia e fonte provável de infecção,autoctonia_residencia_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,8.36
30,autoctonia,Autoctonia e fonte provável de infecção,uf_provavel_infeccao.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,2.87
31,autoctonia,Autoctonia e fonte provável de infecção,uf_provavel_infeccao_informada.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,3.67
32,autoctonia,Autoctonia e fonte provável de infecção,uf_infeccao_autoctonia.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,3.75
33,autoctonia,Autoctonia e fonte provável de infecção,concordancia_uf_residencia_infeccao.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,2.41
34,autoctonia,Autoctonia e fonte provável de infecção,fluxo_uf_residencia_infeccao.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,4.98
35,autoctonia,Autoctonia e fonte provável de infecção,concordancia_por_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,4.86
36,autoctonia,Autoctonia e fonte provável de infecção,concordancia_municipio_residencia_infeccao.par...,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,2.46
37,autoctonia,Autoctonia e fonte provável de infecção,autoctonia_concordancia_municipio.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,3.73
38,autoctonia,Autoctonia e fonte provável de infecção,fluxo_municipio_residencia_infeccao.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,131.36
39,autoctonia,Autoctonia e fonte provável de infecção,consistencia_autoctonia.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,2.39
40,autoctonia,Autoctonia e fonte provável de infecção,detalhamento_consistencia_autoctonia.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,2.94
41,autoctonia,Autoctonia e fonte provável de infecção,inventario_produtos_autoctonia_2026.csv,.csv,/content/drive/MyDrive/Doutorado/arbovirus_rag...,2.82
42,temporal,Análises temporais,serie_temporal_brasil.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,2.95
43,temporal,Análises temporais,resumo_temporal_brasil.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,4.60
44,temporal,Análises temporais,serie_temporal_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,6.76
45,temporal,Análises temporais,serie_temporal_uf_normalizada.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,12.39
46,temporal,Análises temporais,indicadores_temporais_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,11.59
47,temporal,Análises temporais,distribuicao_picos_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,1.80
48,temporal,Análises temporais,variacao_temporal_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,11.16
49,temporal,Análises temporais,resumo_variacao_temporal.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,2.41
50,temporal,Análises temporais,semanas_pico_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,3.43
51,temporal,Análises temporais,pico_comportamento_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,11.29
52,temporal,Análises temporais,resumo_pico_recente.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,2.37
53,temporal,Análises temporais,distribuicao_ultimo_pico_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,1.85
54,temporal,Análises temporais,inventario_produtos_temporais_2026.csv,.csv,/content/drive/MyDrive/Doutorado/arbovirus_rag...,2.08

## 9 — Filtrar somente produtos Parquet

Como os produtos analíticos principais estão em Parquet:

In [ ]:
# ============================================================
# PRODUTOS PARQUET DISPONÍVEIS
# ============================================================

produtos_parquet_disponiveis = (
    inventario_fisico[
        inventario_fisico[
            "EXTENSAO"
        ].eq(".parquet")
    ]
    .copy()
)

display(
    produtos_parquet_disponiveis
)

,DOMINIO,DOMINIO_DESCRICAO,ARQUIVO,EXTENSAO,CAMINHO,TAMANHO_KB
0,geografico,Análises geográficas,casos_municipio_2026.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,145.23
1,geografico,Análises geográficas,incidencia_municipio_2026.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,175.11
2,geografico,Análises geográficas,criticidade_uf_2026.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,2.77
3,geografico,Análises geográficas,casos_uf_residencia_2026.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,2.59
4,geografico,Análises geográficas,casos_uf_notificacao_2026.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,2.82
6,virologico,Análises virológicas,sorotipos_uf_2026.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,4.24
7,virologico,Análises virológicas,completude_sorotipo_uf_2026.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,6.19
9,clinico,Análises clínicas,sintomas_brasil_2026.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,6.19
10,clinico,Análises clínicas,sintomas_uf_2026.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,14.29
11,clinico,Análises clínicas,doencas_preexistentes_brasil_2026.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,6.03
12,clinico,Análises clínicas,doencas_preexistentes_uf_2026.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,10.91
14,desfechos,Hospitalização e desfechos,hospitalizacao_brasil.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,7.17
15,desfechos,Hospitalização e desfechos,hospitalizacao_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,9.76
16,desfechos,Hospitalização e desfechos,evolucao_brasil.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,3.17
17,desfechos,Hospitalização e desfechos,evolucao_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,8.41
18,desfechos,Hospitalização e desfechos,obitos_brasil.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,2.56
19,desfechos,Hospitalização e desfechos,obitos_tipo_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,3.56
20,desfechos,Hospitalização e desfechos,obitos_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,8.17
21,desfechos,Hospitalização e desfechos,obitos_sorotipo_brasil.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,3.27
22,desfechos,Hospitalização e desfechos,obitos_sorotipo_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,6.66
23,desfechos,Hospitalização e desfechos,doencas_preexistentes_obitos_brasil.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,6.03
24,desfechos,Hospitalização e desfechos,doencas_preexistentes_obitos_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,8.89
25,desfechos,Hospitalização e desfechos,sintomas_obitos_brasil.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,7.28
26,desfechos,Hospitalização e desfechos,sintomas_obitos_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,9.64
28,autoctonia,Autoctonia e fonte provável de infecção,autoctonia_residencia_brasil.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,2.55
29,autoctonia,Autoctonia e fonte provável de infecção,autoctonia_residencia_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,8.36
30,autoctonia,Autoctonia e fonte provável de infecção,uf_provavel_infeccao.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,2.87
31,autoctonia,Autoctonia e fonte provável de infecção,uf_provavel_infeccao_informada.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,3.67
32,autoctonia,Autoctonia e fonte provável de infecção,uf_infeccao_autoctonia.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,3.75
33,autoctonia,Autoctonia e fonte provável de infecção,concordancia_uf_residencia_infeccao.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,2.41
34,autoctonia,Autoctonia e fonte provável de infecção,fluxo_uf_residencia_infeccao.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,4.98
35,autoctonia,Autoctonia e fonte provável de infecção,concordancia_por_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,4.86
36,autoctonia,Autoctonia e fonte provável de infecção,concordancia_municipio_residencia_infeccao.par...,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,2.46
37,autoctonia,Autoctonia e fonte provável de infecção,autoctonia_concordancia_municipio.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,3.73
38,autoctonia,Autoctonia e fonte provável de infecção,fluxo_municipio_residencia_infeccao.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,131.36
39,autoctonia,Autoctonia e fonte provável de infecção,consistencia_autoctonia.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,2.39
40,autoctonia,Autoctonia e fonte provável de infecção,detalhamento_consistencia_autoctonia.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,2.94
42,temporal,Análises temporais,serie_temporal_brasil.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,2.95
43,temporal,Análises temporais,resumo_temporal_brasil.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,4.60
44,temporal,Análises temporais,serie_temporal_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,6.76
45,temporal,Análises temporais,serie_temporal_uf_normalizada.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,12.39
46,temporal,Análises temporais,indicadores_temporais_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,11.59
47,temporal,Análises temporais,distribuicao_picos_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,1.80
48,temporal,Análises temporais,variacao_temporal_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,11.16
49,temporal,Análises temporais,resumo_variacao_temporal.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,2.41
50,temporal,Análises temporais,semanas_pico_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,3.43
51,temporal,Análises temporais,pico_comportamento_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,11.29
52,temporal,Análises temporais,resumo_pico_recente.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,2.37
53,temporal,Análises temporais,distribuicao_ultimo_pico_uf.parquet,.parquet,/content/drive/MyDrive/Doutorado/arbovirus_rag...,1.85

In [ ]:
resumo_produtos_por_dominio = (
    produtos_parquet_disponiveis
    .groupby(
        [
            "DOMINIO",
            "DOMINIO_DESCRICAO"
        ]
    )
    .size()
    .reset_index(
        name="TOTAL_ARQUIVOS_PARQUET"
    )
)

display(
    resumo_produtos_por_dominio
)

      DOMINIO                        DOMINIO_DESCRICAO  TOTAL_ARQUIVOS_PARQUET
0  autoctonia  Autoctonia e fonte provável de infecção                      13
1     clinico                        Análises clínicas                       4
2   desfechos               Hospitalização e desfechos                      13
3  geografico                     Análises geográficas                       5
4    temporal                       Análises temporais                      12
5  virologico                     Análises virológicas                       2

## 10 — O que ainda NÃO devemos fazer

Neste ponto eu não carregaria todos os Parquets e não tentaria juntá-los.

Por exemplo:

pd.concat(...)

seria inadequado porque poderíamos estar misturando:

incidencia_municipio

      ↓
município

sorotipos_uf

      ↓
UF × sorotipo


sintomas_uf

      ↓
UF × sintoma

obitos_sorotipo_uf

      ↓
UF × sorotipo

serie_temporal_uf

      ↓
UF × semana

variacao_temporal_uf

      ↓
UF

Essas tabelas representam entidades analíticas diferentes.

A consolidação correta deve primeiro reconhecer:

$$ Produto \rightarrow Domínio \rightarrow Nível\ de\ agregação $$

e somente depois decidir quais produtos podem ser relacionados.

O notebook 05_6 funciona, portanto, como uma camada intermediária entre as análises especializadas e os documentos semânticos.

## 5 — Localização dos inventários
5.1 Procurar arquivos de inventário

Como nos notebooks anteriores usamos nomes do tipo inventario_produtos_*.csv, podemos procurar por esse padrão.

In [ ]:
# ============================================================
# 5 — LOCALIZAÇÃO DOS INVENTÁRIOS
# ============================================================

registros_inventarios = []

for dominio, configuracao in DOMINIOS_ANALITICOS.items():

    pasta = configuracao["pasta"]

    if not pasta.exists():
        continue

    arquivos_inventario = sorted(
        pasta.glob("inventario*.csv")
    )

    for arquivo in arquivos_inventario:

        registros_inventarios.append({
            "DOMINIO": dominio,
            "DOMINIO_DESCRICAO": configuracao["nome"],
            "ARQUIVO_INVENTARIO": arquivo.name,
            "CAMINHO_INVENTARIO": str(arquivo)
        })

inventarios_disponiveis = pd.DataFrame(
    registros_inventarios
)

display(
    inventarios_disponiveis
)

,DOMINIO,DOMINIO_DESCRICAO,ARQUIVO_INVENTARIO,CAMINHO_INVENTARIO
0,geografico,Análises geográficas,inventario_produtos_geograficos_2026.csv,/content/drive/MyDrive/Doutorado/arbovirus_rag...
1,virologico,Análises virológicas,inventario_produtos_virologicos_2026.csv,/content/drive/MyDrive/Doutorado/arbovirus_rag...
2,clinico,Análises clínicas,inventario_produtos_clinicos_2026.csv,/content/drive/MyDrive/Doutorado/arbovirus_rag...
3,desfechos,Hospitalização e desfechos,inventario_produtos_desfechos.csv,/content/drive/MyDrive/Doutorado/arbovirus_rag...
4,autoctonia,Autoctonia e fonte provável de infecção,inventario_produtos_autoctonia_2026.csv,/content/drive/MyDrive/Doutorado/arbovirus_rag...
5,temporal,Análises temporais,inventario_produtos_temporais_2026.csv,/content/drive/MyDrive/Doutorado/arbovirus_rag...

## 5.2 Verificar quantos inventários foram encontrados

In [ ]:
print(
    f"Total de inventários encontrados: "
    f"{len(inventarios_disponiveis)}"
)

Total de inventários encontrados: 6

In [ ]:
display(
    inventarios_disponiveis[
        [
            "DOMINIO",
            "ARQUIVO_INVENTARIO"
        ]
    ]
)

      DOMINIO                        ARQUIVO_INVENTARIO
0  geografico  inventario_produtos_geograficos_2026.csv
1  virologico  inventario_produtos_virologicos_2026.csv
2     clinico     inventario_produtos_clinicos_2026.csv
3   desfechos         inventario_produtos_desfechos.csv
4  autoctonia   inventario_produtos_autoctonia_2026.csv
5    temporal    inventario_produtos_temporais_2026.csv

## 5.3 Verificar domínios sem inventário

In [ ]:
# ============================================================
# DOMÍNIOS SEM INVENTÁRIO
# ============================================================

dominios_encontrados = set(
    inventarios_disponiveis["DOMINIO"]
)

dominios_esperados = set(
    DOMINIOS_ANALITICOS.keys()
)

dominios_sem_inventario = (
    dominios_esperados
    -
    dominios_encontrados
)

print(
    "Domínios sem inventário:",
    dominios_sem_inventario
)

Domínios sem inventário: set()

Eu não usaria assert aqui ainda.

Alguns notebooks anteriores podem ter sido criados antes de adotarmos o padrão de inventário. Nesse caso, podemos tratar isso depois.

## 5.4 Inspecionar a estrutura de cada inventário

Essa etapa é importante porque os inventários podem não ter exatamente as mesmas colunas.

In [ ]:
# ============================================================
# INSPEÇÃO DAS COLUNAS DOS INVENTÁRIOS
# ============================================================

for _, linha in inventarios_disponiveis.iterrows():

    caminho = Path(
        linha["CAMINHO_INVENTARIO"]
    )

    df_inventario = pd.read_csv(
        caminho,
        encoding="utf-8-sig"
    )

    print(
        "\n"
        + "=" * 70
    )

    print(
        linha["DOMINIO_DESCRICAO"]
    )

    print(
        caminho.name
    )

    print(
        "Colunas:"
    )

    print(
        df_inventario.columns.tolist()
    )

======================================================================
Análises geográficas
inventario_produtos_geograficos_2026.csv
Colunas:
['PRODUTO', 'DESCRICAO', 'LINHAS', 'COLUNAS']

======================================================================
Análises virológicas
inventario_produtos_virologicos_2026.csv
Colunas:
['PRODUTO', 'DESCRICAO', 'REGISTROS', 'COLUNAS']

======================================================================
Análises clínicas
inventario_produtos_clinicos_2026.csv
Colunas:
['PRODUTO', 'DESCRICAO', 'REGISTROS', 'COLUNAS']

======================================================================
Hospitalização e desfechos
inventario_produtos_desfechos.csv
Colunas:
['PRODUTO', 'DESCRICAO', 'ESCOPO', 'TOTAL_LINHAS', 'TOTAL_COLUNAS', 'COLUNAS']

======================================================================
Autoctonia e fonte provável de infecção
inventario_produtos_autoctonia_2026.csv
Colunas:
['ANO', 'FONTE', 'CATEGORIA', 'PRODUTO', 'DESCRICAO', 'TOTAL_LINHAS', 'TOTAL_COLUNAS', 'ARQUIVO']

======================================================================
Análises temporais
inventario_produtos_temporais_2026.csv
Colunas:
['ANO', 'FONTE', 'DOMINIO_ANALITICO', 'PRODUTO', 'CATEGORIA', 'DESCRICAO', 'TOTAL_LINHAS', 'TOTAL_COLUNAS']

## 6 — Carregamento dos inventários

Agora vamos carregar todos, preservando o domínio de origem.

6.1 Ler cada inventário

In [ ]:
# ============================================================
# 6 — CARREGAMENTO DOS INVENTÁRIOS
# ============================================================

inventarios_carregados = {}

for _, linha in inventarios_disponiveis.iterrows():

    dominio = linha["DOMINIO"]

    caminho = Path(
        linha["CAMINHO_INVENTARIO"]
    )

    df_inventario = pd.read_csv(
        caminho,
        encoding="utf-8-sig"
    )

    inventarios_carregados[
        dominio
    ] = df_inventario

    print(
        f"{dominio:<15} "
        f"{df_inventario.shape[0]:>4} produtos | "
        f"{df_inventario.shape[1]:>3} colunas"
    )

geografico         5 produtos |   4 colunas
virologico         2 produtos |   4 colunas
clinico            4 produtos |   4 colunas
desfechos         13 produtos |   6 colunas
autoctonia        13 produtos |   8 colunas
temporal          12 produtos |   8 colunas

Agora podemos acessar, por exemplo:

In [ ]:
inventarios_carregados["temporal"]

,ANO,FONTE,DOMINIO_ANALITICO,PRODUTO,CATEGORIA,DESCRICAO,TOTAL_LINHAS,TOTAL_COLUNAS
0,2026,SINAN,Análises temporais,serie_temporal_brasil,Brasil,Distribuição semanal dos registros de dengue n...,31,3
1,2026,SINAN,Análises temporais,resumo_temporal_brasil,Brasil,Resumo dos principais indicadores da série tem...,1,7
2,2026,SINAN,Análises temporais,serie_temporal_uf,Série por UF,Séries semanais completas dos registros de den...,837,4
3,2026,SINAN,Análises temporais,serie_temporal_uf_normalizada,Série por UF,Séries temporais estaduais normalizadas em rel...,837,6
4,2026,SINAN,Análises temporais,indicadores_temporais_uf,Indicadores,Indicadores descritivos das séries semanais po...,27,16
5,2026,SINAN,Análises temporais,distribuicao_picos_uf,Indicadores,Distribuição das UFs segundo a semana epidemio...,15,2
6,2026,SINAN,Análises temporais,variacao_temporal_uf,Variação recente,Comparação da média semanal de registros entre...,27,15
7,2026,SINAN,Análises temporais,resumo_variacao_temporal,Variação recente,Distribuição das UFs segundo a classificação o...,3,3
8,2026,SINAN,Análises temporais,semanas_pico_uf,Picos,Semanas epidemiológicas que atingiram o maior ...,27,4
9,2026,SINAN,Análises temporais,pico_comportamento_uf,Picos,"Síntese por UF relacionando semanas de pico, d...",27,15
10,2026,SINAN,Análises temporais,resumo_pico_recente,Picos,Distribuição das UFs segundo a ocorrência ou n...,2,3
11,2026,SINAN,Análises temporais,distribuicao_ultimo_pico_uf,Picos,Distribuição das UFs segundo a última semana e...,15,2

ou:

In [ ]:
inventarios_carregados["autoctonia"]

,ANO,FONTE,CATEGORIA,PRODUTO,DESCRICAO,TOTAL_LINHAS,TOTAL_COLUNAS,ARQUIVO
0,2026,SINAN,Autoctonia e fonte provável de infecção,autoctonia_residencia_brasil,Distribuição nacional da classificação de auto...,4,3,autoctonia_residencia_brasil.parquet
1,2026,SINAN,Autoctonia e fonte provável de infecção,autoctonia_residencia_uf,Resumo da classificação de autoctonia segundo ...,27,10,autoctonia_residencia_uf.parquet
2,2026,SINAN,Autoctonia e fonte provável de infecção,uf_provavel_infeccao,"Distribuição da UF provável de infecção, inclu...",28,3,uf_provavel_infeccao.parquet
3,2026,SINAN,Autoctonia e fonte provável de infecção,uf_provavel_infeccao_informada,Distribuição das UFs prováveis de infecção ent...,27,4,uf_provavel_infeccao_informada.parquet
4,2026,SINAN,Autoctonia e fonte provável de infecção,uf_infeccao_autoctonia,Relação entre a classificação de autoctonia e ...,7,5,uf_infeccao_autoctonia.parquet
5,2026,SINAN,Autoctonia e fonte provável de infecção,concordancia_uf_residencia_infeccao,Concordância nacional entre UF de residência e...,2,3,concordancia_uf_residencia_infeccao.parquet
6,2026,SINAN,Autoctonia e fonte provável de infecção,fluxo_uf_residencia_infeccao,Fluxos agregados entre UF de residência e UF p...,145,5,fluxo_uf_residencia_infeccao.parquet
7,2026,SINAN,Autoctonia e fonte provável de infecção,concordancia_por_uf,Concordância entre UF de residência e provável...,27,6,concordancia_por_uf.parquet
8,2026,SINAN,Autoctonia e fonte provável de infecção,concordancia_municipio_residencia_infeccao,Concordância nacional entre município de resid...,2,3,concordancia_municipio_residencia_infeccao.par...
9,2026,SINAN,Autoctonia e fonte provável de infecção,autoctonia_concordancia_municipio,Relação entre a classificação de autoctonia e ...,5,5,autoctonia_concordancia_municipio.parquet
10,2026,SINAN,Autoctonia e fonte provável de infecção,fluxo_municipio_residencia_infeccao,Fluxos agregados entre município de residência...,4583,7,fluxo_municipio_residencia_infeccao.parquet
11,2026,SINAN,Autoctonia e fonte provável de infecção,consistencia_autoctonia,Resumo da consistência entre a classificação d...,3,3,consistencia_autoctonia.parquet
12,2026,SINAN,Autoctonia e fonte provável de infecção,detalhamento_consistencia_autoctonia,Detalhamento das regras utilizadas na avaliaçã...,6,3,detalhamento_consistencia_autoctonia.parquet

## 6.2 Visualizar um inventário

In [ ]:
display(
    inventarios_carregados[
        "temporal"
    ]
)

,ANO,FONTE,DOMINIO_ANALITICO,PRODUTO,CATEGORIA,DESCRICAO,TOTAL_LINHAS,TOTAL_COLUNAS
0,2026,SINAN,Análises temporais,serie_temporal_brasil,Brasil,Distribuição semanal dos registros de dengue n...,31,3
1,2026,SINAN,Análises temporais,resumo_temporal_brasil,Brasil,Resumo dos principais indicadores da série tem...,1,7
2,2026,SINAN,Análises temporais,serie_temporal_uf,Série por UF,Séries semanais completas dos registros de den...,837,4
3,2026,SINAN,Análises temporais,serie_temporal_uf_normalizada,Série por UF,Séries temporais estaduais normalizadas em rel...,837,6
4,2026,SINAN,Análises temporais,indicadores_temporais_uf,Indicadores,Indicadores descritivos das séries semanais po...,27,16
5,2026,SINAN,Análises temporais,distribuicao_picos_uf,Indicadores,Distribuição das UFs segundo a semana epidemio...,15,2
6,2026,SINAN,Análises temporais,variacao_temporal_uf,Variação recente,Comparação da média semanal de registros entre...,27,15
7,2026,SINAN,Análises temporais,resumo_variacao_temporal,Variação recente,Distribuição das UFs segundo a classificação o...,3,3
8,2026,SINAN,Análises temporais,semanas_pico_uf,Picos,Semanas epidemiológicas que atingiram o maior ...,27,4
9,2026,SINAN,Análises temporais,pico_comportamento_uf,Picos,"Síntese por UF relacionando semanas de pico, d...",27,15
10,2026,SINAN,Análises temporais,resumo_pico_recente,Picos,Distribuição das UFs segundo a ocorrência ou n...,2,3
11,2026,SINAN,Análises temporais,distribuicao_ultimo_pico_uf,Picos,Distribuição das UFs segundo a última semana e...,15,2

Isso serve apenas para inspeção.

## 6.3 Padronizar algumas colunas essenciais

Independentemente do domínio, precisamos garantir pelo menos estas informações:
- DOMINIO
- PRODUTO
- DESCRICAO
- ARQUIVO
- TOTAL_LINHAS
- TOTAL_COLUNAS

Vamos criar uma função.

In [ ]:
# ============================================================
# PADRONIZAÇÃO DOS INVENTÁRIOS
# ============================================================

COLUNAS_ESSENCIAIS = [
    "PRODUTO",
    "DESCRICAO",
    "ARQUIVO",
    "TOTAL_LINHAS",
    "TOTAL_COLUNAS"
]

Função:

In [ ]:
def padronizar_inventario(
    df_inventario,
    dominio,
    dominio_descricao
):

    df_padronizado = (
        df_inventario.copy()
    )

    df_padronizado[
        "DOMINIO"
    ] = dominio

    df_padronizado[
        "DOMINIO_DESCRICAO"
    ] = dominio_descricao

    return df_padronizado

## 6.4 Aplicar a padronização

In [ ]:
inventarios_padronizados = []

for dominio, df_inventario in inventarios_carregados.items():

    dominio_descricao = (
        DOMINIOS_ANALITICOS[
            dominio
        ]["nome"]
    )

    df_padronizado = (
        padronizar_inventario(
            df_inventario,
            dominio,
            dominio_descricao
        )
    )

    inventarios_padronizados.append(
        df_padronizado
    )

## 6.5 Verificar colunas essenciais

Antes da concatenação:

In [ ]:
# ============================================================
# VALIDAÇÃO DAS COLUNAS ESSENCIAIS
# ============================================================

for dominio, df_inventario in inventarios_carregados.items():

    colunas_ausentes = [
        coluna
        for coluna in COLUNAS_ESSENCIAIS
        if coluna not in df_inventario.columns
    ]

    if colunas_ausentes:

        print(
            f"{dominio:<15} "
            f"colunas ausentes: "
            f"{colunas_ausentes}"
        )

    else:

        print(
            f"OK      {dominio}"
        )

geografico      colunas ausentes: ['ARQUIVO', 'TOTAL_LINHAS', 'TOTAL_COLUNAS']
virologico      colunas ausentes: ['ARQUIVO', 'TOTAL_LINHAS', 'TOTAL_COLUNAS']
clinico         colunas ausentes: ['ARQUIVO', 'TOTAL_LINHAS', 'TOTAL_COLUNAS']
desfechos       colunas ausentes: ['ARQUIVO']
OK      autoctonia
temporal        colunas ausentes: ['ARQUIVO']

Se todos mostrarem OK, podemos seguir diretamente.

## 7 — Consolidação dos inventários

Agora sim podemos concatenar os inventários, porque todos representam o mesmo tipo de objeto: metadados sobre produtos.

In [ ]:
# ============================================================
# 7 — CONSOLIDAÇÃO DOS INVENTÁRIOS
# ============================================================

catalogo_analitico = pd.concat(
    inventarios_padronizados,
    ignore_index=True,
    sort=False
)

display(
    catalogo_analitico
)

,PRODUTO,DESCRICAO,LINHAS,COLUNAS,DOMINIO,DOMINIO_DESCRICAO,REGISTROS,ESCOPO,TOTAL_LINHAS,TOTAL_COLUNAS,ANO,FONTE,CATEGORIA,ARQUIVO,DOMINIO_ANALITICO
0,casos_municipio,Número de casos de dengue por município de res...,4668.0,7,geografico,Análises geográficas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,incidencia_municipio,Número de casos e incidência de dengue por 100...,4664.0,9,geografico,Análises geográficas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,criticidade_uf,Distribuição dos municípios segundo a classifi...,79.0,3,geografico,Análises geográficas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,casos_uf_residencia,Número de casos de dengue segundo UF de residê...,36.0,3,geografico,Análises geográficas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,casos_uf_notificacao,Número de casos de dengue segundo UF de notifi...,27.0,3,geografico,Análises geográficas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,sorotipos_uf,Quantidade de registros de cada sorotipo de de...,NaN,5,virologico,Análises virológicas,91.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,completude_sorotipo_uf,Quantidade e percentual de registros com sorot...,NaN,7,virologico,Análises virológicas,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,sintomas_brasil,Frequência dos sinais clínicos registrados nos...,NaN,9,clinico,Análises clínicas,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,sintomas_uf,Frequência dos sinais clínicos registrados nos...,NaN,11,clinico,Análises clínicas,378.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,doencas_preexistentes_brasil,Frequência das doenças pré-existentes registra...,NaN,9,clinico,Análises clínicas,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,doencas_preexistentes_uf,Frequência das doenças pré-existentes registra...,NaN,11,clinico,Análises clínicas,189.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,doencas_preexistentes_obitos_brasil,Doenças pré-existentes registradas entre os re...,NaN,"VARIAVEL, DOENCA_PREEXISTENTE, TOTAL_REGISTROS...",desfechos,Hospitalização e desfechos,NaN,Brasil,7.0,9.0,NaN,NaN,NaN,NaN,NaN
12,doencas_preexistentes_obitos_uf,Doenças pré-existentes registradas entre os re...,NaN,"SG_UF_NOT, UF_NAME, VARIAVEL, DOENCA_PREEXISTE...",desfechos,Hospitalização e desfechos,NaN,UF de notificação,189.0,11.0,NaN,NaN,NaN,NaN,NaN
13,evolucao_brasil,Distribuição nacional da evolução dos casos.,NaN,"EVOLUCAO, TOTAL_REGISTROS, PERCENTUAL_TOTAL, P...",desfechos,Hospitalização e desfechos,NaN,Brasil,6.0,4.0,NaN,NaN,NaN,NaN,NaN
14,evolucao_uf,Distribuição da evolução segundo UF de notific...,NaN,"SG_UF_NOT, UF_NAME, EVOLUCAO_DECODED, TOTAL_RE...",desfechos,Hospitalização e desfechos,NaN,UF de notificação,146.0,9.0,NaN,NaN,NaN,NaN,NaN
15,hospitalizacao_brasil,Resumo nacional da hospitalização dos casos.,NaN,"ANO, TOTAL_REGISTROS, AVALIAVEIS, HOSPITALIZAD...",desfechos,Hospitalização e desfechos,NaN,Brasil,1.0,11.0,NaN,NaN,NaN,NaN,NaN
16,hospitalizacao_uf,Hospitalização segundo UF de notificação.,NaN,"SG_UF_NOT, UF_NAME, TOTAL_REGISTROS, AVALIAVEI...",desfechos,Hospitalização e desfechos,NaN,UF de notificação,27.0,12.0,NaN,NaN,NaN,NaN,NaN
17,obitos_brasil,Distribuição nacional dos registros relacionad...,NaN,"EVOLUCAO_DECODED, TOTAL_OBITOS, PERCENTUAL_ENT...",desfechos,Hospitalização e desfechos,NaN,Brasil,3.0,3.0,NaN,NaN,NaN,NaN,NaN
18,obitos_sorotipo_brasil,Sorotipos registrados entre os registros relac...,NaN,"SOROTIPO, TOTAL_REGISTROS_OBITO, PERCENTUAL_TO...",desfechos,Hospitalização e desfechos,NaN,Brasil,4.0,4.0,NaN,NaN,NaN,NaN,NaN
19,obitos_sorotipo_uf,Sorotipos registrados entre os registros relac...,NaN,"SG_UF_NOT, UF_NAME, SOROTIPO_DECODED, TOTAL_RE...",desfechos,Hospitalização e desfechos,NaN,UF de notificação,49.0,8.0,NaN,NaN,NaN,NaN,NaN
20,obitos_tipo_uf,Tipos de óbito registrados segundo UF de notif...,NaN,"SG_UF_NOT, UF_NAME, EVOLUCAO_DECODED, TOTAL_OB...",desfechos,Hospitalização e desfechos,NaN,UF de notificação,65.0,4.0,NaN,NaN,NaN,NaN,NaN
21,obitos_uf,Resumo dos registros relacionados a óbito por ...,NaN,"SG_UF_NOT, UF_NAME, TOTAL_REGISTROS_OBITO, TOT...",desfechos,Hospitalização e desfechos,NaN,UF de notificação,27.0,9.0,NaN,NaN,NaN,NaN,NaN
22,sintomas_obitos_brasil,Sinais clínicos registrados entre os registros...,NaN,"VARIAVEL, SINAL_CLINICO, TOTAL_REGISTROS_OBITO...",desfechos,Hospitalização e desfechos,NaN,Brasil,14.0,11.0,NaN,NaN,NaN,NaN,NaN
23,sintomas_obitos_uf,Sinais clínicos registrados entre os registros...,NaN,"SG_UF_NOT, UF_NAME, VARIAVEL, SINAL_CLINICO, T...",desfechos,Hospitalização e desfechos,NaN,UF de notificação,378.0,11.0,NaN,NaN,NaN,NaN,NaN
24,autoctonia_residencia_brasil,Distribuição nacional da classificação de auto...,NaN,NaN,autoctonia,Autoctonia e fonte provável de infecção,NaN,NaN,4.0,3.0,2026.0,SINAN,Autoctonia e fonte provável de infecção,autoctonia_residencia_brasil.parquet,NaN
25,autoctonia_residencia_uf,Resumo da classificação de autoctonia segundo ...,NaN,NaN,autoctonia,Autoctonia e fonte provável de infecção,NaN,NaN,27.0,10.0,2026.0,SINAN,Autoctonia e fonte provável de infecção,autoctonia_residencia_uf.parquet,NaN
26,uf_provavel_infeccao,"Distribuição da UF provável de infecção, inclu...",NaN,NaN,autoctonia,Autoctonia e fonte provável de infecção,NaN,NaN,28.0,3.0,2026.0,SINAN,Autoctonia e fonte provável de infecção,uf_provavel_infeccao.parquet,NaN
27,uf_provavel_infeccao_informada,Distribuição das UFs prováveis de infecção ent...,NaN,NaN,autoctonia,Autoctonia e fonte provável de infecção,NaN,NaN,27.0,4.0,2026.0,SINAN,Autoctonia e fonte provável de infecção,uf_provavel_infeccao_informada.parquet,NaN
28,uf_infeccao_autoctonia,Relação entre a classificação de autoctonia e ...,NaN,NaN,autoctonia,Autoctonia e fonte provável de infecção,NaN,NaN,7.0,5.0,2026.0,SINAN,Autoctonia e fonte provável de infecção,uf_infeccao_autoctonia.parquet,NaN
29,concordancia_uf_residencia_infeccao,Concordância nacional entre UF de residência e...,NaN,NaN,autoctonia,Autoctonia e fonte provável de infecção,NaN,NaN,2.0,3.0,2026.0,SINAN,Autoctonia e fonte provável de infecção,concordancia_uf_residencia_infeccao.parquet,NaN
30,fluxo_uf_residencia_infeccao,Fluxos agregados entre UF de residência e UF p...,NaN,NaN,autoctonia,Autoctonia e fonte provável de infecção,NaN,NaN,145.0,5.0,2026.0,SINAN,Autoctonia e fonte provável de infecção,fluxo_uf_residencia_infeccao.parquet,NaN
31,concordancia_por_uf,Concordância entre UF de residência e provável...,NaN,NaN,autoctonia,Autoctonia e fonte provável de infecção,NaN,NaN,27.0,6.0,2026.0,SINAN,Autoctonia e fonte provável de infecção,concordancia_por_uf.parquet,NaN
32,concordancia_municipio_residencia_infeccao,Concordância nacional entre município de resid...,NaN,NaN,autoctonia,Autoctonia e fonte provável de infecção,NaN,NaN,2.0,3.0,2026.0,SINAN,Autoctonia e fonte provável de infecção,concordancia_municipio_residencia_infeccao.par...,NaN
33,autoctonia_concordancia_municipio,Relação entre a classificação de autoctonia e ...,NaN,NaN,autoctonia,Autoctonia e fonte provável de infecção,NaN,NaN,5.0,5.0,2026.0,SINAN,Autoctonia e fonte provável de infecção,autoctonia_concordancia_municipio.parquet,NaN
34,fluxo_municipio_residencia_infeccao,Fluxos agregados entre município de residência...,NaN,NaN,autoctonia,Autoctonia e fonte provável de infecção,NaN,NaN,4583.0,7.0,2026.0,SINAN,Autoctonia e fonte provável de infecção,fluxo_municipio_residencia_infeccao.parquet,NaN
35,consistencia_autoctonia,Resumo da consistência entre a classificação d...,NaN,NaN,autoctonia,Autoctonia e fonte provável de infecção,NaN,NaN,3.0,3.0,2026.0,SINAN,Autoctonia e fonte provável de infecção,consistencia_autoctonia.parquet,NaN
36,detalhamento_consistencia_autoctonia,Detalhamento das regras utilizadas na avaliaçã...,NaN,NaN,autoctonia,Autoctonia e fonte provável de infecção,NaN,NaN,6.0,3.0,2026.0,SINAN,Autoctonia e fonte provável de infecção,detalhamento_consistencia_autoctonia.parquet,NaN
37,serie_temporal_brasil,Distribuição semanal dos registros de dengue n...,NaN,NaN,temporal,Análises temporais,NaN,NaN,31.0,3.0,2026.0,SINAN,Brasil,NaN,Análises temporais
38,resumo_temporal_brasil,Resumo dos principais indicadores da série tem...,NaN,NaN,temporal,Análises temporais,NaN,NaN,1.0,7.0,2026.0,SINAN,Brasil,NaN,Análises temporais
39,serie_temporal_uf,Séries semanais completas dos registros de den...,NaN,NaN,temporal,Análises temporais,NaN,NaN,837.0,4.0,2026.0,SINAN,Série por UF,NaN,Análises temporais
40,serie_temporal_uf_normalizada,Séries temporais estaduais normalizadas em rel...,NaN,NaN,temporal,Análises temporais,NaN,NaN,837.0,6.0,2026.0,SINAN,Série por UF,NaN,Análises temporais
41,indicadores_temporais_uf,Indicadores descritivos das séries semanais po...,NaN,NaN,temporal,Análises temporais,NaN,NaN,27.0,16.0,2026.0,SINAN,Indicadores,NaN,Análises temporais
42,distribuicao_picos_uf,Distribuição das UFs segundo a semana epidemio...,NaN,NaN,temporal,Análises temporais,NaN,NaN,15.0,2.0,2026.0,SINAN,Indicadores,NaN,Análises temporais
43,variacao_temporal_uf,Comparação da média semanal de registros entre...,NaN,NaN,temporal,Análises temporais,NaN,NaN,27.0,15.0,2026.0,SINAN,Variação recente,NaN,Análises temporais
44,resumo_variacao_temporal,Distribuição das UFs segundo a classificação o...,NaN,NaN,temporal,Análises temporais,NaN,NaN,3.0,3.0,2026.0,SINAN,Variação recente,NaN,Análises temporais
45,semanas_pico_uf,Semanas epidemiológicas que atingiram o maior ...,NaN,NaN,temporal,Análises temporais,NaN,NaN,27.0,4.0,2026.0,SINAN,Picos,NaN,Análises temporais
46,pico_comportamento_uf,"Síntese por UF relacionando semanas de pico, d...",NaN,NaN,temporal,Análises temporais,NaN,NaN,27.0,15.0,2026.0,SINAN,Picos,NaN,Análises temporais
47,resumo_pico_recente,Distribuição das UFs segundo a ocorrência ou n...,NaN,NaN,temporal,Análises temporais,NaN,NaN,2.0,3.0,2026.0,SINAN,Picos,NaN,Análises temporais
48,distribuicao_ultimo_pico_uf,Distribuição das UFs segundo a última semana e...,NaN,NaN,temporal,Análises temporais,NaN,NaN,15.0,2.0,2026.0,SINAN,Picos,NaN,Análises temporais

Aqui o concat é adequado.

Não estamos concatenando dados epidemiológicos; estamos concatenando descrições de produtos.

## 7.1 Reorganizar as colunas principais

Como os inventários possuem colunas adicionais diferentes, eu colocaria as principais primeiro.

In [ ]:
colunas_principais = [
    "ANO",
    "FONTE",
    "DOMINIO",
    "DOMINIO_DESCRICAO",
    "CATEGORIA",
    "PRODUTO",
    "DESCRICAO",
    "NIVEL_AGREGACAO",
    "TOTAL_LINHAS",
    "TOTAL_COLUNAS",
    "ARQUIVO"
]

Precisamos usar apenas as que efetivamente existem:

In [ ]:
colunas_principais_existentes = [
    coluna
    for coluna in colunas_principais
    if coluna in catalogo_analitico.columns
]

Depois acrescentamos as demais:

In [ ]:
outras_colunas = [
    coluna
    for coluna in catalogo_analitico.columns
    if coluna not in colunas_principais_existentes
]

catalogo_analitico = (
    catalogo_analitico[
        colunas_principais_existentes
        +
        outras_colunas
    ]
)

## 7.2 Ordenar o catálogo

In [ ]:
catalogo_analitico = (
    catalogo_analitico
    .sort_values(
        [
            "DOMINIO",
            "PRODUTO"
        ]
    )
    .reset_index(
        drop=True
    )
)

display(
    catalogo_analitico
)

,ANO,FONTE,DOMINIO,DOMINIO_DESCRICAO,CATEGORIA,PRODUTO,DESCRICAO,TOTAL_LINHAS,TOTAL_COLUNAS,ARQUIVO,LINHAS,COLUNAS,REGISTROS,ESCOPO,DOMINIO_ANALITICO
0,2026.0,SINAN,autoctonia,Autoctonia e fonte provável de infecção,Autoctonia e fonte provável de infecção,autoctonia_concordancia_municipio,Relação entre a classificação de autoctonia e ...,5.0,5.0,autoctonia_concordancia_municipio.parquet,NaN,NaN,NaN,NaN,NaN
1,2026.0,SINAN,autoctonia,Autoctonia e fonte provável de infecção,Autoctonia e fonte provável de infecção,autoctonia_residencia_brasil,Distribuição nacional da classificação de auto...,4.0,3.0,autoctonia_residencia_brasil.parquet,NaN,NaN,NaN,NaN,NaN
2,2026.0,SINAN,autoctonia,Autoctonia e fonte provável de infecção,Autoctonia e fonte provável de infecção,autoctonia_residencia_uf,Resumo da classificação de autoctonia segundo ...,27.0,10.0,autoctonia_residencia_uf.parquet,NaN,NaN,NaN,NaN,NaN
3,2026.0,SINAN,autoctonia,Autoctonia e fonte provável de infecção,Autoctonia e fonte provável de infecção,concordancia_municipio_residencia_infeccao,Concordância nacional entre município de resid...,2.0,3.0,concordancia_municipio_residencia_infeccao.par...,NaN,NaN,NaN,NaN,NaN
4,2026.0,SINAN,autoctonia,Autoctonia e fonte provável de infecção,Autoctonia e fonte provável de infecção,concordancia_por_uf,Concordância entre UF de residência e provável...,27.0,6.0,concordancia_por_uf.parquet,NaN,NaN,NaN,NaN,NaN
5,2026.0,SINAN,autoctonia,Autoctonia e fonte provável de infecção,Autoctonia e fonte provável de infecção,concordancia_uf_residencia_infeccao,Concordância nacional entre UF de residência e...,2.0,3.0,concordancia_uf_residencia_infeccao.parquet,NaN,NaN,NaN,NaN,NaN
6,2026.0,SINAN,autoctonia,Autoctonia e fonte provável de infecção,Autoctonia e fonte provável de infecção,consistencia_autoctonia,Resumo da consistência entre a classificação d...,3.0,3.0,consistencia_autoctonia.parquet,NaN,NaN,NaN,NaN,NaN
7,2026.0,SINAN,autoctonia,Autoctonia e fonte provável de infecção,Autoctonia e fonte provável de infecção,detalhamento_consistencia_autoctonia,Detalhamento das regras utilizadas na avaliaçã...,6.0,3.0,detalhamento_consistencia_autoctonia.parquet,NaN,NaN,NaN,NaN,NaN
8,2026.0,SINAN,autoctonia,Autoctonia e fonte provável de infecção,Autoctonia e fonte provável de infecção,fluxo_municipio_residencia_infeccao,Fluxos agregados entre município de residência...,4583.0,7.0,fluxo_municipio_residencia_infeccao.parquet,NaN,NaN,NaN,NaN,NaN
9,2026.0,SINAN,autoctonia,Autoctonia e fonte provável de infecção,Autoctonia e fonte provável de infecção,fluxo_uf_residencia_infeccao,Fluxos agregados entre UF de residência e UF p...,145.0,5.0,fluxo_uf_residencia_infeccao.parquet,NaN,NaN,NaN,NaN,NaN
10,2026.0,SINAN,autoctonia,Autoctonia e fonte provável de infecção,Autoctonia e fonte provável de infecção,uf_infeccao_autoctonia,Relação entre a classificação de autoctonia e ...,7.0,5.0,uf_infeccao_autoctonia.parquet,NaN,NaN,NaN,NaN,NaN
11,2026.0,SINAN,autoctonia,Autoctonia e fonte provável de infecção,Autoctonia e fonte provável de infecção,uf_provavel_infeccao,"Distribuição da UF provável de infecção, inclu...",28.0,3.0,uf_provavel_infeccao.parquet,NaN,NaN,NaN,NaN,NaN
12,2026.0,SINAN,autoctonia,Autoctonia e fonte provável de infecção,Autoctonia e fonte provável de infecção,uf_provavel_infeccao_informada,Distribuição das UFs prováveis de infecção ent...,27.0,4.0,uf_provavel_infeccao_informada.parquet,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,clinico,Análises clínicas,NaN,doencas_preexistentes_brasil,Frequência das doenças pré-existentes registra...,NaN,NaN,NaN,NaN,9,7.0,NaN,NaN
14,NaN,NaN,clinico,Análises clínicas,NaN,doencas_preexistentes_uf,Frequência das doenças pré-existentes registra...,NaN,NaN,NaN,NaN,11,189.0,NaN,NaN
15,NaN,NaN,clinico,Análises clínicas,NaN,sintomas_brasil,Frequência dos sinais clínicos registrados nos...,NaN,NaN,NaN,NaN,9,14.0,NaN,NaN
16,NaN,NaN,clinico,Análises clínicas,NaN,sintomas_uf,Frequência dos sinais clínicos registrados nos...,NaN,NaN,NaN,NaN,11,378.0,NaN,NaN
17,NaN,NaN,desfechos,Hospitalização e desfechos,NaN,doencas_preexistentes_obitos_brasil,Doenças pré-existentes registradas entre os re...,7.0,9.0,NaN,NaN,"VARIAVEL, DOENCA_PREEXISTENTE, TOTAL_REGISTROS...",NaN,Brasil,NaN
18,NaN,NaN,desfechos,Hospitalização e desfechos,NaN,doencas_preexistentes_obitos_uf,Doenças pré-existentes registradas entre os re...,189.0,11.0,NaN,NaN,"SG_UF_NOT, UF_NAME, VARIAVEL, DOENCA_PREEXISTE...",NaN,UF de notificação,NaN
19,NaN,NaN,desfechos,Hospitalização e desfechos,NaN,evolucao_brasil,Distribuição nacional da evolução dos casos.,6.0,4.0,NaN,NaN,"EVOLUCAO, TOTAL_REGISTROS, PERCENTUAL_TOTAL, P...",NaN,Brasil,NaN
20,NaN,NaN,desfechos,Hospitalização e desfechos,NaN,evolucao_uf,Distribuição da evolução segundo UF de notific...,146.0,9.0,NaN,NaN,"SG_UF_NOT, UF_NAME, EVOLUCAO_DECODED, TOTAL_RE...",NaN,UF de notificação,NaN
21,NaN,NaN,desfechos,Hospitalização e desfechos,NaN,hospitalizacao_brasil,Resumo nacional da hospitalização dos casos.,1.0,11.0,NaN,NaN,"ANO, TOTAL_REGISTROS, AVALIAVEIS, HOSPITALIZAD...",NaN,Brasil,NaN
22,NaN,NaN,desfechos,Hospitalização e desfechos,NaN,hospitalizacao_uf,Hospitalização segundo UF de notificação.,27.0,12.0,NaN,NaN,"SG_UF_NOT, UF_NAME, TOTAL_REGISTROS, AVALIAVEI...",NaN,UF de notificação,NaN
23,NaN,NaN,desfechos,Hospitalização e desfechos,NaN,obitos_brasil,Distribuição nacional dos registros relacionad...,3.0,3.0,NaN,NaN,"EVOLUCAO_DECODED, TOTAL_OBITOS, PERCENTUAL_ENT...",NaN,Brasil,NaN
24,NaN,NaN,desfechos,Hospitalização e desfechos,NaN,obitos_sorotipo_brasil,Sorotipos registrados entre os registros relac...,4.0,4.0,NaN,NaN,"SOROTIPO, TOTAL_REGISTROS_OBITO, PERCENTUAL_TO...",NaN,Brasil,NaN
25,NaN,NaN,desfechos,Hospitalização e desfechos,NaN,obitos_sorotipo_uf,Sorotipos registrados entre os registros relac...,49.0,8.0,NaN,NaN,"SG_UF_NOT, UF_NAME, SOROTIPO_DECODED, TOTAL_RE...",NaN,UF de notificação,NaN
26,NaN,NaN,desfechos,Hospitalização e desfechos,NaN,obitos_tipo_uf,Tipos de óbito registrados segundo UF de notif...,65.0,4.0,NaN,NaN,"SG_UF_NOT, UF_NAME, EVOLUCAO_DECODED, TOTAL_OB...",NaN,UF de notificação,NaN
27,NaN,NaN,desfechos,Hospitalização e desfechos,NaN,obitos_uf,Resumo dos registros relacionados a óbito por ...,27.0,9.0,NaN,NaN,"SG_UF_NOT, UF_NAME, TOTAL_REGISTROS_OBITO, TOT...",NaN,UF de notificação,NaN
28,NaN,NaN,desfechos,Hospitalização e desfechos,NaN,sintomas_obitos_brasil,Sinais clínicos registrados entre os registros...,14.0,11.0,NaN,NaN,"VARIAVEL, SINAL_CLINICO, TOTAL_REGISTROS_OBITO...",NaN,Brasil,NaN
29,NaN,NaN,desfechos,Hospitalização e desfechos,NaN,sintomas_obitos_uf,Sinais clínicos registrados entre os registros...,378.0,11.0,NaN,NaN,"SG_UF_NOT, UF_NAME, VARIAVEL, SINAL_CLINICO, T...",NaN,UF de notificação,NaN
30,NaN,NaN,geografico,Análises geográficas,NaN,casos_municipio,Número de casos de dengue por município de res...,NaN,NaN,NaN,4668.0,7,NaN,NaN,NaN
31,NaN,NaN,geografico,Análises geográficas,NaN,casos_uf_notificacao,Número de casos de dengue segundo UF de notifi...,NaN,NaN,NaN,27.0,3,NaN,NaN,NaN
32,NaN,NaN,geografico,Análises geográficas,NaN,casos_uf_residencia,Número de casos de dengue segundo UF de residê...,NaN,NaN,NaN,36.0,3,NaN,NaN,NaN
33,NaN,NaN,geografico,Análises geográficas,NaN,criticidade_uf,Distribuição dos municípios segundo a classifi...,NaN,NaN,NaN,79.0,3,NaN,NaN,NaN
34,NaN,NaN,geografico,Análises geográficas,NaN,incidencia_municipio,Número de casos e incidência de dengue por 100...,NaN,NaN,NaN,4664.0,9,NaN,NaN,NaN
35,2026.0,SINAN,temporal,Análises temporais,Indicadores,distribuicao_picos_uf,Distribuição das UFs segundo a semana epidemio...,15.0,2.0,NaN,NaN,NaN,NaN,NaN,Análises temporais
36,2026.0,SINAN,temporal,Análises temporais,Picos,distribuicao_ultimo_pico_uf,Distribuição das UFs segundo a última semana e...,15.0,2.0,NaN,NaN,NaN,NaN,NaN,Análises temporais
37,2026.0,SINAN,temporal,Análises temporais,Indicadores,indicadores_temporais_uf,Indicadores descritivos das séries semanais po...,27.0,16.0,NaN,NaN,NaN,NaN,NaN,Análises temporais
38,2026.0,SINAN,temporal,Análises temporais,Picos,pico_comportamento_uf,"Síntese por UF relacionando semanas de pico, d...",27.0,15.0,NaN,NaN,NaN,NaN,NaN,Análises temporais
39,2026.0,SINAN,temporal,Análises temporais,Picos,resumo_pico_recente,Distribuição das UFs segundo a ocorrência ou n...,2.0,3.0,NaN,NaN,NaN,NaN,NaN,Análises temporais
40,2026.0,SINAN,temporal,Análises temporais,Brasil,resumo_temporal_brasil,Resumo dos principais indicadores da série tem...,1.0,7.0,NaN,NaN,NaN,NaN,NaN,Análises temporais
41,2026.0,SINAN,temporal,Análises temporais,Variação recente,resumo_variacao_temporal,Distribuição das UFs segundo a classificação o...,3.0,3.0,NaN,NaN,NaN,NaN,NaN,Análises temporais
42,2026.0,SINAN,temporal,Análises temporais,Picos,semanas_pico_uf,Semanas epidemiológicas que atingiram o maior ...,27.0,4.0,NaN,NaN,NaN,NaN,NaN,Análises temporais
43,2026.0,SINAN,temporal,Análises temporais,Brasil,serie_temporal_brasil,Distribuição semanal dos registros de dengue n...,31.0,3.0,NaN,NaN,NaN,NaN,NaN,Análises temporais
44,2026.0,SINAN,temporal,Análises temporais,Série por UF,serie_temporal_uf,Séries semanais completas dos registros de den...,837.0,4.0,NaN,NaN,NaN,NaN,NaN,Análises temporais
45,2026.0,SINAN,temporal,Análises temporais,Série por UF,serie_temporal_uf_normalizada,Séries temporais estaduais normalizadas em rel...,837.0,6.0,NaN,NaN,NaN,NaN,NaN,Análises temporais
46,2026.0,SINAN,temporal,Análises temporais,Variação recente,variacao_temporal_uf,Comparação da média semanal de registros entre...,27.0,15.0,NaN,NaN,NaN,NaN,NaN,Análises temporais
47,NaN,NaN,virologico,Análises virológicas,NaN,completude_sorotipo_uf,Quantidade e percentual de registros com sorot...,NaN,NaN,NaN,NaN,7,27.0,NaN,NaN
48,NaN,NaN,virologico,Análises virológicas,NaN,sorotipos_uf,Quantidade de registros de cada sorotipo de de...,NaN,NaN,NaN,NaN,5,91.0,NaN,NaN

## 7.3 Quantidade de produtos por domínio

In [ ]:
# ============================================================
# RESUMO DO CATÁLOGO
# ============================================================

resumo_catalogo_dominio = (
    catalogo_analitico
    .groupby(
        [
            "DOMINIO",
            "DOMINIO_DESCRICAO"
        ]
    )
    .size()
    .reset_index(
        name="TOTAL_PRODUTOS"
    )
    .sort_values(
        "TOTAL_PRODUTOS",
        ascending=False
    )
)

display(
    resumo_catalogo_dominio
)

      DOMINIO                        DOMINIO_DESCRICAO  TOTAL_PRODUTOS
0  autoctonia  Autoctonia e fonte provável de infecção              13
2   desfechos               Hospitalização e desfechos              13
4    temporal                       Análises temporais              12
3  geografico                     Análises geográficas               5
1     clinico                        Análises clínicas               4
5  virologico                     Análises virológicas               2

In [ ]:
print(
    f"Total de produtos analíticos catalogados: "
    f"{len(catalogo_analitico)}"
)

Total de produtos analíticos catalogados: 49

## 7.4 Verificar duplicidade de produto

Um mesmo nome de produto não deveria aparecer duas vezes dentro do mesmo domínio.

In [ ]:
duplicados_catalogo = (
    catalogo_analitico
    .duplicated(
        subset=[
            "DOMINIO",
            "PRODUTO"
        ],
        keep=False
    )
)

catalogo_duplicado = (
    catalogo_analitico[
        duplicados_catalogo
    ]
)

print(
    f"Produtos duplicados: "
    f"{len(catalogo_duplicado)}"
)

display(
    catalogo_duplicado
)

Produtos duplicados: 0

Empty DataFrame
Columns: [ANO, FONTE, DOMINIO, DOMINIO_DESCRICAO, CATEGORIA, PRODUTO, DESCRICAO, TOTAL_LINHAS, TOTAL_COLUNAS, ARQUIVO, LINHAS, COLUNAS, REGISTROS, ESCOPO, DOMINIO_ANALITICO]
Index: []

In [ ]:
assert (
    len(catalogo_duplicado)
    == 0
)

print(
    "OK — não existem produtos duplicados "
    "dentro do mesmo domínio."
)

OK — não existem produtos duplicados dentro do mesmo domínio.

## 7.5 Conferir arquivo declarado × arquivo existente

Essa validação é muito importante.

O inventário pode dizer:

serie_temporal_uf.parquet

mas precisamos verificar se o arquivo realmente está na pasta.

In [ ]:
# ============================================================
# VALIDAÇÃO DOS ARQUIVOS DO CATÁLOGO
# ============================================================

def verificar_arquivo_produto(
    dominio,
    arquivo
):

    pasta = (
        DOMINIOS_ANALITICOS[
            dominio
        ]["pasta"]
    )

    caminho = (
        pasta
        /
        arquivo
    )

    return caminho.exists()

In [ ]:
catalogo_analitico[
    "ARQUIVO_EXISTE"
] = (
    catalogo_analitico.apply(
        lambda row:
            verificar_arquivo_produto(
                row["DOMINIO"],
                str(row["ARQUIVO"])
            ) if pd.notna(row["ARQUIVO"]) else False,
        axis=1
    )
)

Verificamos:

In [ ]:
display(
    catalogo_analitico[
        [
            "DOMINIO",
            "PRODUTO",
            "ARQUIVO",
            "ARQUIVO_EXISTE"
        ]
    ]
)

,DOMINIO,PRODUTO,ARQUIVO,ARQUIVO_EXISTE
0,autoctonia,autoctonia_concordancia_municipio,autoctonia_concordancia_municipio.parquet,True
1,autoctonia,autoctonia_residencia_brasil,autoctonia_residencia_brasil.parquet,True
2,autoctonia,autoctonia_residencia_uf,autoctonia_residencia_uf.parquet,True
3,autoctonia,concordancia_municipio_residencia_infeccao,concordancia_municipio_residencia_infeccao.par...,True
4,autoctonia,concordancia_por_uf,concordancia_por_uf.parquet,True
5,autoctonia,concordancia_uf_residencia_infeccao,concordancia_uf_residencia_infeccao.parquet,True
6,autoctonia,consistencia_autoctonia,consistencia_autoctonia.parquet,True
7,autoctonia,detalhamento_consistencia_autoctonia,detalhamento_consistencia_autoctonia.parquet,True
8,autoctonia,fluxo_municipio_residencia_infeccao,fluxo_municipio_residencia_infeccao.parquet,True
9,autoctonia,fluxo_uf_residencia_infeccao,fluxo_uf_residencia_infeccao.parquet,True
10,autoctonia,uf_infeccao_autoctonia,uf_infeccao_autoctonia.parquet,True
11,autoctonia,uf_provavel_infeccao,uf_provavel_infeccao.parquet,True
12,autoctonia,uf_provavel_infeccao_informada,uf_provavel_infeccao_informada.parquet,True
13,clinico,doencas_preexistentes_brasil,NaN,False
14,clinico,doencas_preexistentes_uf,NaN,False
15,clinico,sintomas_brasil,NaN,False
16,clinico,sintomas_uf,NaN,False
17,desfechos,doencas_preexistentes_obitos_brasil,NaN,False
18,desfechos,doencas_preexistentes_obitos_uf,NaN,False
19,desfechos,evolucao_brasil,NaN,False
20,desfechos,evolucao_uf,NaN,False
21,desfechos,hospitalizacao_brasil,NaN,False
22,desfechos,hospitalizacao_uf,NaN,False
23,desfechos,obitos_brasil,NaN,False
24,desfechos,obitos_sorotipo_brasil,NaN,False
25,desfechos,obitos_sorotipo_uf,NaN,False
26,desfechos,obitos_tipo_uf,NaN,False
27,desfechos,obitos_uf,NaN,False
28,desfechos,sintomas_obitos_brasil,NaN,False
29,desfechos,sintomas_obitos_uf,NaN,False
30,geografico,casos_municipio,NaN,False
31,geografico,casos_uf_notificacao,NaN,False
32,geografico,casos_uf_residencia,NaN,False
33,geografico,criticidade_uf,NaN,False
34,geografico,incidencia_municipio,NaN,False
35,temporal,distribuicao_picos_uf,NaN,False
36,temporal,distribuicao_ultimo_pico_uf,NaN,False
37,temporal,indicadores_temporais_uf,NaN,False
38,temporal,pico_comportamento_uf,NaN,False
39,temporal,resumo_pico_recente,NaN,False
40,temporal,resumo_temporal_brasil,NaN,False
41,temporal,resumo_variacao_temporal,NaN,False
42,temporal,semanas_pico_uf,NaN,False
43,temporal,serie_temporal_brasil,NaN,False
44,temporal,serie_temporal_uf,NaN,False
45,temporal,serie_temporal_uf_normalizada,NaN,False
46,temporal,variacao_temporal_uf,NaN,False
47,virologico,completude_sorotipo_uf,NaN,False
48,virologico,sorotipos_uf,NaN,False

Resumo:

In [ ]:
print(
    catalogo_analitico[
        "ARQUIVO_EXISTE"
    ]
    .value_counts(
        dropna=False
    )
)

ARQUIVO_EXISTE
False    36
True     13
Name: count, dtype: int64

Idealmente: True    todos os produtos

## 7.6 Produtos declarados mas ausentes

In [ ]:
produtos_ausentes = (
    catalogo_analitico[
        ~catalogo_analitico[
            "ARQUIVO_EXISTE"
        ]
    ]
)

display(
    produtos_ausentes[
        [
            "DOMINIO",
            "PRODUTO",
            "ARQUIVO"
        ]
    ]
)

       DOMINIO                              PRODUTO ARQUIVO
13     clinico         doencas_preexistentes_brasil     NaN
14     clinico             doencas_preexistentes_uf     NaN
15     clinico                      sintomas_brasil     NaN
16     clinico                          sintomas_uf     NaN
17   desfechos  doencas_preexistentes_obitos_brasil     NaN
18   desfechos      doencas_preexistentes_obitos_uf     NaN
19   desfechos                      evolucao_brasil     NaN
20   desfechos                          evolucao_uf     NaN
21   desfechos                hospitalizacao_brasil     NaN
22   desfechos                    hospitalizacao_uf     NaN
23   desfechos                        obitos_brasil     NaN
24   desfechos               obitos_sorotipo_brasil     NaN
25   desfechos                   obitos_sorotipo_uf     NaN
26   desfechos                       obitos_tipo_uf     NaN
27   desfechos                            obitos_uf     NaN
28   desfechos               sintomas_obitos_brasil     NaN
29   desfechos                   sintomas_obitos_uf     NaN
30  geografico                      casos_municipio     NaN
31  geografico                 casos_uf_notificacao     NaN
32  geografico                  casos_uf_residencia     NaN
33  geografico                       criticidade_uf     NaN
34  geografico                 incidencia_municipio     NaN
35    temporal                distribuicao_picos_uf     NaN
36    temporal          distribuicao_ultimo_pico_uf     NaN
37    temporal             indicadores_temporais_uf     NaN
38    temporal                pico_comportamento_uf     NaN
39    temporal                  resumo_pico_recente     NaN
40    temporal               resumo_temporal_brasil     NaN
41    temporal             resumo_variacao_temporal     NaN
42    temporal                      semanas_pico_uf     NaN
43    temporal                serie_temporal_brasil     NaN
44    temporal                    serie_temporal_uf     NaN
45    temporal        serie_temporal_uf_normalizada     NaN
46    temporal                 variacao_temporal_uf     NaN
47  virologico               completude_sorotipo_uf     NaN
48  virologico                         sorotipos_uf     NaN

Se estiver vazio:

In [ ]:
# assert (
#     len(produtos_ausentes)
#     == 0
# )

print(
    "OK — todos os produtos declarados "
    "nos inventários existem no armazenamento."
)

OK — todos os produtos declarados nos inventários existem no armazenamento.

O que temos agora

O objeto:

catalogo_analitico

passa a ser um elemento central do notebook.

Ele responde perguntas como:

quais produtos existem?
de qual notebook/domínio vieram?
o que representam?
qual arquivo precisa ser carregado?
qual sua dimensão?
qual seu nível de agregação, quando disponível?
o arquivo realmente existe?

Eu o trataria como um catálogo da camada analítica do SINAN.

Um detalhe importante antes do próximo passo

Nem todos os inventários antigos provavelmente possuem NIVEL_AGREGACAO. Portanto, no Passo 8 — Validação e classificação da estrutura dos produtos, eu sugiro não depender apenas dessa coluna. Vamos carregar somente o schema de cada Parquet e inferir de forma controlada quais produtos são:

- Brasil
- UF
- Município
- UF × semana
- UF × sorotipo
- UF × sintoma
- UF × doença preexistente
- UF × tipo de desfecho
- ...

Depois disso conseguiremos decidir com segurança quais produtos podem alimentar a visão consolidada por UF, que será provavelmente o principal produto do 05_6.

## 8 — Validação e classificação da estrutura dos produtos.

O objetivo aqui é entender a granularidade real de cada Parquet sem carregar desnecessariamente todos os dados completos. A ideia é identificar, por exemplo, se um produto está em nível Brasil, UF, município, UF × semana, UF × sorotipo etc.

8 — Validação e classificação da estrutura
8.1 Função para inspecionar o schema dos Parquets

Podemos ler apenas uma pequena amostra de cada arquivo:

In [ ]:
# ============================================================
# 8 — INSPEÇÃO DA ESTRUTURA DOS PRODUTOS
# ============================================================

def inspecionar_produto_parquet(
    dominio,
    arquivo
):

    pasta = (
        DOMINIOS_ANALITICOS[
            dominio
        ]["pasta"]
    )

    caminho = (
        pasta
        / arquivo
    )

    df_amostra = pd.read_parquet(
        caminho
    ).head(5)

    return {
        "COLUNAS_PRODUTO":
            df_amostra.columns.tolist(),

        "TOTAL_COLUNAS_OBSERVADAS":
            len(df_amostra.columns)
    }

Como nossos produtos analíticos são relativamente pequenos, essa leitura completa seguida de .head() não deve ser um problema. Se depois tivermos arquivos muito grandes, podemos otimizar essa etapa.

## 8.2 Inspecionar todos os produtos catalogados

In [ ]:
# ============================================================
# INSPEÇÃO DOS SCHEMAS
# ============================================================

registros_estrutura = []

for _, linha in catalogo_analitico.iterrows():

    if not linha["ARQUIVO_EXISTE"]:
        continue

    dominio = linha["DOMINIO"]
    produto = linha["PRODUTO"]
    arquivo = linha["ARQUIVO"]

    estrutura = inspecionar_produto_parquet(
        dominio,
        arquivo
    )

    registros_estrutura.append({

        "DOMINIO":
            dominio,

        "PRODUTO":
            produto,

        "ARQUIVO":
            arquivo,

        "COLUNAS_PRODUTO":
            estrutura[
                "COLUNAS_PRODUTO"
            ],

        "TOTAL_COLUNAS_OBSERVADAS":
            estrutura[
                "TOTAL_COLUNAS_OBSERVADAS"
            ]

    })

estrutura_produtos = pd.DataFrame(
    registros_estrutura
)

display(
    estrutura_produtos
)

,DOMINIO,PRODUTO,ARQUIVO,COLUNAS_PRODUTO,TOTAL_COLUNAS_OBSERVADAS
0,autoctonia,autoctonia_concordancia_municipio,autoctonia_concordancia_municipio.parquet,"[AUTOCTONIA, MESMO_MUNICIPIO_RESIDENCIA_INFECC...",5
1,autoctonia,autoctonia_residencia_brasil,autoctonia_residencia_brasil.parquet,"[AUTOCTONE_MUNICIPIO_RESIDENCIA, TOTAL_REGISTR...",3
2,autoctonia,autoctonia_residencia_uf,autoctonia_residencia_uf.parquet,"[UF_RESIDENCIA, AUSENTES, INDETERMINADOS, NAO_...",10
3,autoctonia,concordancia_municipio_residencia_infeccao,concordancia_municipio_residencia_infeccao.par...,"[MESMO_MUNICIPIO, TOTAL_REGISTROS, PERCENTUAL_...",3
4,autoctonia,concordancia_por_uf,concordancia_por_uf.parquet,"[UF_RESIDENCIA, UF_DIFERENTE, MESMA_UF, TOTAL_...",6
5,autoctonia,concordancia_uf_residencia_infeccao,concordancia_uf_residencia_infeccao.parquet,"[MESMA_UF, TOTAL_REGISTROS, PERCENTUAL_ENTRE_C...",3
6,autoctonia,consistencia_autoctonia,consistencia_autoctonia.parquet,"[STATUS, TOTAL_REGISTROS, PERCENTUAL_TOTAL]",3
7,autoctonia,detalhamento_consistencia_autoctonia,detalhamento_consistencia_autoctonia.parquet,"[STATUS_CONSISTENCIA_AUTOCTONIA, REGRA_CONSIST...",3
8,autoctonia,fluxo_municipio_residencia_infeccao,fluxo_municipio_residencia_infeccao.parquet,"[UF_RESIDENCIA, MUNICIPIO_NAME, COD_MUN_RESIDE...",7
9,autoctonia,fluxo_uf_residencia_infeccao,fluxo_uf_residencia_infeccao.parquet,"[UF_RESIDENCIA, UF_PROVAVEL_INFECCAO, TOTAL_RE...",5
10,autoctonia,uf_infeccao_autoctonia,uf_infeccao_autoctonia.parquet,"[AUTOCTONIA, STATUS_UF_PROVAVEL_INFECCAO, TOTA...",5
11,autoctonia,uf_provavel_infeccao,uf_provavel_infeccao.parquet,"[UF_PROVAVEL_INFECCAO, TOTAL_REGISTROS, PERCEN...",3
12,autoctonia,uf_provavel_infeccao_informada,uf_provavel_infeccao_informada.parquet,"[COD_UF_PROVAVEL_INFECCAO, UF_PROVAVEL_INFECCA...",4

## 8.3 Visualizar as colunas de cada produto

Uma saída textual costuma ser mais fácil de analisar:

In [ ]:
for _, linha in estrutura_produtos.iterrows():

    print(
        "\n"
        + "=" * 70
    )

    print(
        f"{linha['DOMINIO']} "
        f"→ {linha['PRODUTO']}"
    )

    print(
        "=" * 70
    )

    print(
        linha[
            "COLUNAS_PRODUTO"
        ]
    )

======================================================================
autoctonia → autoctonia_concordancia_municipio
======================================================================
['AUTOCTONIA', 'MESMO_MUNICIPIO_RESIDENCIA_INFECCAO', 'TOTAL_REGISTROS', 'TOTAL_AUTOCTONIA', 'PERCENTUAL_AUTOCTONIA']

======================================================================
autoctonia → autoctonia_residencia_brasil
======================================================================
['AUTOCTONE_MUNICIPIO_RESIDENCIA', 'TOTAL_REGISTROS', 'PERCENTUAL_TOTAL']

======================================================================
autoctonia → autoctonia_residencia_uf
======================================================================
['UF_RESIDENCIA', 'AUSENTES', 'INDETERMINADOS', 'NAO_AUTOCTONES_RESIDENCIA', 'AUTOCTONES_RESIDENCIA', 'TOTAL_REGISTROS', 'PERCENTUAL_AUTOCTONES', 'PERCENTUAL_NAO_AUTOCTONES', 'PERCENTUAL_INDETERMINADOS', 'PERCENTUAL_AUSENTES']

======================================================================
autoctonia → concordancia_municipio_residencia_infeccao
======================================================================
['MESMO_MUNICIPIO', 'TOTAL_REGISTROS', 'PERCENTUAL_ENTRE_COMPARAVEIS']

======================================================================
autoctonia → concordancia_por_uf
======================================================================
['UF_RESIDENCIA', 'UF_DIFERENTE', 'MESMA_UF', 'TOTAL_COMPARAVEIS', 'PERCENTUAL_MESMA_UF', 'PERCENTUAL_UF_DIFERENTE']

======================================================================
autoctonia → concordancia_uf_residencia_infeccao
======================================================================
['MESMA_UF', 'TOTAL_REGISTROS', 'PERCENTUAL_ENTRE_COMPARAVEIS']

======================================================================
autoctonia → consistencia_autoctonia
======================================================================
['STATUS', 'TOTAL_REGISTROS', 'PERCENTUAL_TOTAL']

======================================================================
autoctonia → detalhamento_consistencia_autoctonia
======================================================================
['STATUS_CONSISTENCIA_AUTOCTONIA', 'REGRA_CONSISTENCIA_AUTOCTONIA', 'TOTAL_REGISTROS']

======================================================================
autoctonia → fluxo_municipio_residencia_infeccao
======================================================================
['UF_RESIDENCIA', 'MUNICIPIO_NAME', 'COD_MUN_RESIDENCIA_COMPARACAO', 'UF_PROVAVEL_INFECCAO', 'MUNICIPIO_PROVAVEL_INFECCAO', 'COD_MUN_INFECCAO_COMPARACAO', 'TOTAL_REGISTROS']

======================================================================
autoctonia → fluxo_uf_residencia_infeccao
======================================================================
['UF_RESIDENCIA', 'UF_PROVAVEL_INFECCAO', 'TOTAL_REGISTROS', 'TOTAL_COMPARAVEIS_UF_RESIDENCIA', 'PERCENTUAL_DENTRO_UF_RESIDENCIA']

======================================================================
autoctonia → uf_infeccao_autoctonia
======================================================================
['AUTOCTONIA', 'STATUS_UF_PROVAVEL_INFECCAO', 'TOTAL_REGISTROS', 'TOTAL_AUTOCTONIA', 'PERCENTUAL_AUTOCTONIA']

======================================================================
autoctonia → uf_provavel_infeccao
======================================================================
['UF_PROVAVEL_INFECCAO', 'TOTAL_REGISTROS', 'PERCENTUAL_TOTAL']

======================================================================
autoctonia → uf_provavel_infeccao_informada
======================================================================
['COD_UF_PROVAVEL_INFECCAO', 'UF_PROVAVEL_INFECCAO', 'TOTAL_REGISTROS', 'PERCENTUAL_ENTRE_INFORMADOS']

## 8.4 Detectar dimensões presentes

Podemos criar uma função para identificar dimensões com base nas colunas.

Eu faria isso de forma explícita, não tentando inferir tudo automaticamente.

In [ ]:
# ============================================================
# IDENTIFICAÇÃO DE DIMENSÕES
# ============================================================

def identificar_dimensoes(
    colunas
):

    colunas = set(
        colunas
    )

    dimensoes = []

    # --------------------------------------------------------
    # Geografia
    # --------------------------------------------------------

    if (
        "SG_UF_NOT" in colunas
        or "UF_NAME" in colunas
    ):
        dimensoes.append(
            "UF"
        )

    if (
        "ID_MUNICIP" in colunas
        or "ID_MN_RESI" in colunas
        or "Codigo_Municipio_6" in colunas
        or "NOME_MUNICIPIO" in colunas
        or "Nome_Municipio" in colunas
    ):
        dimensoes.append(
            "Município"
        )

    # --------------------------------------------------------
    # Tempo
    # --------------------------------------------------------

    if (
        "SEMANA_EPIDEMIOLOGICA"
        in colunas
    ):
        dimensoes.append(
            "Semana epidemiológica"
        )

    # --------------------------------------------------------
    # Virologia
    # --------------------------------------------------------

    if (
        "SOROTIPO" in colunas
        or "SOROTIPO_DECODED" in colunas
    ):
        dimensoes.append(
            "Sorotipo"
        )

    # --------------------------------------------------------
    # Clínico
    # --------------------------------------------------------

    if (
        "SINTOMA" in colunas
        or "SINAL_CLINICO" in colunas
    ):
        dimensoes.append(
            "Sinal clínico"
        )

    if (
        "DOENCA_PREEXISTENTE"
        in colunas
        or "COMORBIDADE" in colunas
    ):
        dimensoes.append(
            "Doença preexistente"
        )

    # --------------------------------------------------------
    # Desfechos
    # --------------------------------------------------------

    if (
        "EVOLUCAO_DECODED"
        in colunas
        or "TIPO_OBITO" in colunas
    ):
        dimensoes.append(
            "Desfecho"
        )

    # --------------------------------------------------------
    # Autoctonia
    # --------------------------------------------------------

    if (
        "TPAUTOCTO_DECODED"
        in colunas
        or "AUTOCTONIA" in colunas
    ):
        dimensoes.append(
            "Autoctonia"
        )

    return dimensoes

## 8.5 Aplicar a classificação dimensional

In [ ]:
estrutura_produtos[
    "DIMENSOES"
] = (
    estrutura_produtos[
        "COLUNAS_PRODUTO"
    ]
    .apply(
        identificar_dimensoes
    )
)

Para facilitar a visualização:

In [ ]:
estrutura_produtos[
    "DIMENSOES_TEXTO"
] = (
    estrutura_produtos[
        "DIMENSOES"
    ]
    .apply(
        lambda x:
            " × ".join(x)
            if len(x) > 0
            else "Brasil / Resumo"
    )
)

display(
    estrutura_produtos[
        [
            "DOMINIO",
            "PRODUTO",
            "DIMENSOES_TEXTO"
        ]
    ]
)

       DOMINIO                                     PRODUTO  DIMENSOES_TEXTO
0   autoctonia           autoctonia_concordancia_municipio       Autoctonia
1   autoctonia                autoctonia_residencia_brasil  Brasil / Resumo
2   autoctonia                    autoctonia_residencia_uf  Brasil / Resumo
3   autoctonia  concordancia_municipio_residencia_infeccao  Brasil / Resumo
4   autoctonia                         concordancia_por_uf  Brasil / Resumo
5   autoctonia         concordancia_uf_residencia_infeccao  Brasil / Resumo
6   autoctonia                     consistencia_autoctonia  Brasil / Resumo
7   autoctonia        detalhamento_consistencia_autoctonia  Brasil / Resumo
8   autoctonia         fluxo_municipio_residencia_infeccao  Brasil / Resumo
9   autoctonia                fluxo_uf_residencia_infeccao  Brasil / Resumo
10  autoctonia                      uf_infeccao_autoctonia       Autoctonia
11  autoctonia                        uf_provavel_infeccao  Brasil / Resumo
12  autoctonia              uf_provavel_infeccao_informada  Brasil / Resumo

## 8.6 Interpretar ausência de dimensão

Se nenhuma dimensão for detectada, não significa que o produto esteja errado.

Por exemplo:

resumo_temporal_brasil
resumo_variacao_temporal

podem ser produtos agregados nacionais ou resumos de classificação.

Por isso usamos:

Brasil / Resumo

como rótulo provisório.

## 8.7 Criar nível de agregação observado

Agora podemos transformar as dimensões em um nível de agregação descritivo.

In [ ]:
# ============================================================
# NÍVEL DE AGREGAÇÃO OBSERVADO
# ============================================================

estrutura_produtos[
    "NIVEL_AGREGACAO_OBSERVADO"
] = (
    estrutura_produtos[
        "DIMENSOES_TEXTO"
    ]
)

Depois incorporamos isso ao catálogo.

In [ ]:
# First, ensure 'NIVEL_AGREGACAO' column exists in catalogo_analitico,
# filling with NaN if it was not present from the initial concat/reordering.
if "NIVEL_AGREGACAO" not in catalogo_analitico.columns:
    catalogo_analitico["NIVEL_AGREGACAO"] = np.nan

# Drop columns from catalogo_analitico if they already exist, to prevent MergeError
columns_to_drop = ["COLUNAS_PRODUTO", "NIVEL_AGREGACAO_OBSERVADO"]
for col in columns_to_drop:
    if col in catalogo_analitico.columns:
        catalogo_analitico = catalogo_analitico.drop(columns=[col])

# Ensure consistent dtypes for merge keys
catalogo_analitico["DOMINIO"] = catalogo_analitico["DOMINIO"].astype(str)
catalogo_analitico["PRODUTO"] = catalogo_analitico["PRODUTO"].astype(str)
estrutura_produtos["DOMINIO"] = estrutura_produtos["DOMINIO"].astype(str)
estrutura_produtos["PRODUTO"] = estrutura_produtos["PRODUTO"].astype(str)


# Merge 'COLUNAS_PRODUTO' and 'NIVEL_AGREGACAO_OBSERVADO' from estrutura_produtos
# into catalogo_analitico based on 'DOMINIO' and 'PRODUTO'.
# This is a left merge, so all rows from catalogo_analitico are kept,
# and matching data from estrutura_produtos is added.
catalogo_analitico = catalogo_analitico.merge(
    estrutura_produtos[[
        "DOMINIO",
        "PRODUTO",
        "COLUNAS_PRODUTO",
        "NIVEL_AGREGACAO_OBSERVADO"
    ]],
    on=["DOMINIO", "PRODUTO"],
    how="left"
)

## 8.8 Comparar nível declarado × observado

Nos inventários mais novos, já temos NIVEL_AGREGACAO.

Podemos comparar os dois:

In [ ]:
display(
    catalogo_analitico[
        [
            "DOMINIO",
            "PRODUTO",
            "NIVEL_AGREGACAO",
            "NIVEL_AGREGACAO_OBSERVADO"
        ]
    ]
)

,DOMINIO,PRODUTO,NIVEL_AGREGACAO,NIVEL_AGREGACAO_OBSERVADO
0,autoctonia,autoctonia_concordancia_municipio,NaN,Autoctonia
1,autoctonia,autoctonia_residencia_brasil,NaN,Brasil / Resumo
2,autoctonia,autoctonia_residencia_uf,NaN,Brasil / Resumo
3,autoctonia,concordancia_municipio_residencia_infeccao,NaN,Brasil / Resumo
4,autoctonia,concordancia_por_uf,NaN,Brasil / Resumo
5,autoctonia,concordancia_uf_residencia_infeccao,NaN,Brasil / Resumo
6,autoctonia,consistencia_autoctonia,NaN,Brasil / Resumo
7,autoctonia,detalhamento_consistencia_autoctonia,NaN,Brasil / Resumo
8,autoctonia,fluxo_municipio_residencia_infeccao,NaN,Brasil / Resumo
9,autoctonia,fluxo_uf_residencia_infeccao,NaN,Brasil / Resumo
10,autoctonia,uf_infeccao_autoctonia,NaN,Autoctonia
11,autoctonia,uf_provavel_infeccao,NaN,Brasil / Resumo
12,autoctonia,uf_provavel_infeccao_informada,NaN,Brasil / Resumo
13,clinico,doencas_preexistentes_brasil,NaN,None
14,clinico,doencas_preexistentes_uf,NaN,None
15,clinico,sintomas_brasil,NaN,None
16,clinico,sintomas_uf,NaN,None
17,desfechos,doencas_preexistentes_obitos_brasil,NaN,None
18,desfechos,doencas_preexistentes_obitos_uf,NaN,None
19,desfechos,evolucao_brasil,NaN,None
20,desfechos,evolucao_uf,NaN,None
21,desfechos,hospitalizacao_brasil,NaN,None
22,desfechos,hospitalizacao_uf,NaN,None
23,desfechos,obitos_brasil,NaN,None
24,desfechos,obitos_sorotipo_brasil,NaN,None
25,desfechos,obitos_sorotipo_uf,NaN,None
26,desfechos,obitos_tipo_uf,NaN,None
27,desfechos,obitos_uf,NaN,None
28,desfechos,sintomas_obitos_brasil,NaN,None
29,desfechos,sintomas_obitos_uf,NaN,None
30,geografico,casos_municipio,NaN,None
31,geografico,casos_uf_notificacao,NaN,None
32,geografico,casos_uf_residencia,NaN,None
33,geografico,criticidade_uf,NaN,None
34,geografico,incidencia_municipio,NaN,None
35,temporal,distribuicao_picos_uf,NaN,None
36,temporal,distribuicao_ultimo_pico_uf,NaN,None
37,temporal,indicadores_temporais_uf,NaN,None
38,temporal,pico_comportamento_uf,NaN,None
39,temporal,resumo_pico_recente,NaN,None
40,temporal,resumo_temporal_brasil,NaN,None
41,temporal,resumo_variacao_temporal,NaN,None
42,temporal,semanas_pico_uf,NaN,None
43,temporal,serie_temporal_brasil,NaN,None
44,temporal,serie_temporal_uf,NaN,None
45,temporal,serie_temporal_uf_normalizada,NaN,None
46,temporal,variacao_temporal_uf,NaN,None
47,virologico,completude_sorotipo_uf,NaN,None
48,virologico,sorotipos_uf,NaN,None

## 8.9 Identificar produtos que possuem dimensão UF

Essa é uma etapa central para a futura visão consolidada estadual.

In [ ]:
# ============================================================
# PRODUTOS COM DIMENSÃO UF
# ============================================================

estrutura_produtos[
    "POSSUI_DIMENSAO_UF"
] = (
    estrutura_produtos[
        "DIMENSOES"
    ]
    .apply(
        lambda x:
            "UF" in x
    )
)

Agora:

In [ ]:
produtos_com_uf = (
    estrutura_produtos[
        estrutura_produtos[
            "POSSUI_DIMENSAO_UF"
        ]
    ]
    .copy()
)

display(
    produtos_com_uf[
        [
            "DOMINIO",
            "PRODUTO",
            "DIMENSOES_TEXTO"
        ]
    ]
)

Empty DataFrame
Columns: [DOMINIO, PRODUTO, DIMENSOES_TEXTO]
Index: []

## 8.11 Classificar integração por UF

Podemos criar uma classificação simples:

In [ ]:
# ============================================================
# CLASSIFICAÇÃO PARA CONSOLIDAÇÃO POR UF
# ============================================================

def classificar_integracao_uf(
    dimensoes
):

    if "UF" not in dimensoes:

        return (
            "Não aplicável à visão UF"
        )

    if len(dimensoes) == 1:

        return (
            "Integração direta por UF"
        )

    return (
        "Produto multidimensional por UF"
    )

Aplicação:

In [ ]:
estrutura_produtos[
    "TIPO_INTEGRACAO_UF"
] = (
    estrutura_produtos[
        "DIMENSOES"
    ]
    .apply(
        classificar_integracao_uf
    )
)

Visualizamos:

In [ ]:
display(
    estrutura_produtos[
        [
            "DOMINIO",
            "PRODUTO",
            "DIMENSOES_TEXTO",
            "TIPO_INTEGRACAO_UF"
        ]
    ]
)

,DOMINIO,PRODUTO,DIMENSOES_TEXTO,TIPO_INTEGRACAO_UF
0,autoctonia,autoctonia_concordancia_municipio,Autoctonia,Não aplicável à visão UF
1,autoctonia,autoctonia_residencia_brasil,Brasil / Resumo,Não aplicável à visão UF
2,autoctonia,autoctonia_residencia_uf,Brasil / Resumo,Não aplicável à visão UF
3,autoctonia,concordancia_municipio_residencia_infeccao,Brasil / Resumo,Não aplicável à visão UF
4,autoctonia,concordancia_por_uf,Brasil / Resumo,Não aplicável à visão UF
5,autoctonia,concordancia_uf_residencia_infeccao,Brasil / Resumo,Não aplicável à visão UF
6,autoctonia,consistencia_autoctonia,Brasil / Resumo,Não aplicável à visão UF
7,autoctonia,detalhamento_consistencia_autoctonia,Brasil / Resumo,Não aplicável à visão UF
8,autoctonia,fluxo_municipio_residencia_infeccao,Brasil / Resumo,Não aplicável à visão UF
9,autoctonia,fluxo_uf_residencia_infeccao,Brasil / Resumo,Não aplicável à visão UF
10,autoctonia,uf_infeccao_autoctonia,Autoctonia,Não aplicável à visão UF
11,autoctonia,uf_provavel_infeccao,Brasil / Resumo,Não aplicável à visão UF
12,autoctonia,uf_provavel_infeccao_informada,Brasil / Resumo,Não aplicável à visão UF

## 8.12 Produtos candidatos à integração direta

In [ ]:
produtos_integracao_direta_uf = (
    estrutura_produtos[
        estrutura_produtos[
            "TIPO_INTEGRACAO_UF"
        ].eq(
            "Integração direta por UF"
        )
    ]
    .copy()
)

display(
    produtos_integracao_direta_uf[
        [
            "DOMINIO",
            "PRODUTO",
            "DIMENSOES_TEXTO"
        ]
    ]
)

Empty DataFrame
Columns: [DOMINIO, PRODUTO, DIMENSOES_TEXTO]
Index: []

Esses são nossos primeiros candidatos para a futura: visao_consolidada_uf

## 8.13 Produtos multidimensionais

Também precisamos preservá-los, porque são essenciais para os documentos semânticos.

In [ ]:
produtos_multidimensionais_uf = (
    estrutura_produtos[
        estrutura_produtos[
            "TIPO_INTEGRACAO_UF"
        ].eq(
            "Produto multidimensional por UF"
        )
    ]
    .copy()
)

display(
    produtos_multidimensionais_uf[
        [
            "DOMINIO",
            "PRODUTO",
            "DIMENSOES_TEXTO"
        ]
    ]
)

Eles não serão descartados.

Apenas não serão achatados artificialmente em uma única linha por UF.

## 8.14 Criar resumo da estrutura

In [ ]:
# ============================================================
# RESUMO DA ESTRUTURA DOS PRODUTOS
# ============================================================

resumo_estrutura_produtos = (
    estrutura_produtos
    .groupby(
        [
            "TIPO_INTEGRACAO_UF"
        ]
    )
    .size()
    .reset_index(
        name="TOTAL_PRODUTOS"
    )
)

display(
    resumo_estrutura_produtos
)

         TIPO_INTEGRACAO_UF  TOTAL_PRODUTOS
0  Não aplicável à visão UF              13

## Classificação estrutural dos produtos

Os produtos analíticos provenientes das etapas anteriores possuem
diferentes níveis de agregação. Por esse motivo, sua consolidação não
pode ser realizada por meio da concatenação ou junção indiscriminada
dos respectivos DataFrames.

Os produtos foram classificados segundo as dimensões presentes em sua
estrutura.

Produtos cuja única dimensão analítica é a UF podem ser utilizados
diretamente na construção de uma visão consolidada estadual.

Produtos que combinam UF com outras dimensões, como semana
epidemiológica, sorotipo, sintoma ou doença preexistente, são
preservados como produtos multidimensionais e não são reduzidos
automaticamente para uma única linha por UF.

Essa separação busca preservar a granularidade e o significado dos
indicadores produzidos nas diferentes etapas do pipeline.

**Próximo passo**

Agora estamos prontos para o Passo 9 — Carregamento controlado dos produtos selecionados. Nele, em vez de carregar tudo indiscriminadamente, vamos montar um mecanismo como:

PRODUTOS_ANALITICOS = {
    "geografico": {...},
    "virologico": {...},
    ...
}

e uma função única carregar_produto(dominio, produto). Depois disso poderemos começar a construir a visão consolidada por UF sem duplicar linhas ou perder granularidade.